### PR TITLE
fix(ssrf): add octal notation to SSRF dataset 934110

### PR DESCRIPTION
**Pull request by karelorigin**
Block octal notation (and octal dotless) for the AWS metadata endpoint.

### CODE REVIEW

**Comment by azurit** [comment]
Hi @terjanq, thanks for sending this!

**Comment by azurit** [comment]
Hi @karelorigin , thanks for sending this!

**Comment by fzipi** [comment]
Doing a review on the rules and tests, we should be detecting this in PL2. See [the rule](https://github.com/coreruleset/coreruleset/blob/ac1576aedf9007289671b02bf191d53c835c1460/rules/REQUEST-934-APPLICATION-ATTACK-GENERIC.conf#L163), and [the test](https://github.com/coreruleset/coreruleset/blob/ac1576aedf9007289671b02bf191d53c835c1460/tests/regression/tests/REQUEST-934-APPLICATION-ATTACK-GENERIC/934120.yaml#L169). This was detected as bypass in PL3, so I'm pretty sure something else needs to be fixed.

**Comment by dune73** [comment]
@karelorigin would you mind quoting the bug bounty ID (without the prefix) here?

**Comment by karelorigin** [comment]
@dune73, the ID is the suffix of the branch name used in this PR (6SQKXAJC)

**Comment by dune73** [comment]
Got you. Thanks.

**Comment by dune73** [comment]
### CRS Bug Bounty PR assessment

* **Rules affected** (list rules): FIXME
* **Paranoia Level addressed** (1, 2, 3, 4, full or explain): FIXME
* **FTW passes** (yes or no) : FIXME
* **Rule(s) picked for solution** (correct or not-correct or explain) : FIXME
* **Risk for false positives** (irrelevant, adequate, substantial or explain) : FIXME
* **Regular expression quality** (inspirational, decent base, needs work, adequate or explain) : FIXME
* **Documentation** (needs work, adequate or explain) : FIXME
* **Tests** (none or some or adequate) : FIXME
&nbsp;
* **Verdict** (Unusable, inspirational, usable, almost perfect or perfect) : FIXME

_This is not meant to be final. As a CRS dev, feel free to comment below and edit this form directly. As committer or observer, feel free to comment below with feedback and we will think about updating the assessment accordingly._

**Comment by fzipi** [comment]
Hi @karelorigin! 

We chatted about this. While the rule solves the problem, it's easily bypasseable. The solution is to change `ARGS` for `REQUEST_COOKIES|!REQUEST_COOKIES:/__utm/|REQUEST_COOKIES_NAMES|REQUEST_FILENAME|ARGS_NAMES|ARGS|XML:/*` on `934120`.

**Comment by karelorigin** [comment]
Hi @fzipi,

Indeed! Even though it goes beyond the patching 'assignment', I'm more than happy to change `934120` and provide additional test cases for it :)

**Comment by karelorigin** [comment]
> Risk for false positives (irrelevant, adequate, substantial or explain): yes

I know that these reviews are not final but I feel to see how this risks false positives. Was this perhaps the result of a copy-paste? Any details on that would be great, helps me resolve issues, assuming there are any :)

**Comment by fzipi** [comment]
> > Risk for false positives (irrelevant, adequate, substantial or explain): yes
> 
> I know that these reviews are not final but I feel to see how this risks false positives. Was this perhaps the result of a copy-paste? Any details on that would be great, helps me resolve issues, assuming there are any :)

I think it was just bad copy & paste. 😄

**Comment by lifeforms** [comment]
Yeah you should read it more like YES!!!! 💪🥳 No it was indeed a paste error.

**Comment by fzipi** [comment]
@karelorigin Unless you have additional comments, I'll be merging this one tomorrow.

**Comment by karelorigin** [comment]
@fzipi, thanks, but I'd still like to incorporate the feedback you gave me earlier: 

> Hi @karelorigin!
> 
> We chatted about this. While the rule solves the problem, it's easily bypasseable. The solution is to change `ARGS` for `REQUEST_COOKIES|!REQUEST_COOKIES:/__utm/|REQUEST_COOKIES_NAMES|REQUEST_FILENAME|ARGS_NAMES|ARGS|XML:/*` on `934120`.

**Comment by fzipi** [comment]
Awesome. We merged now the core updates to 934120, so you can make your magic when ready.

**Comment by fzipi** [comment]
@karelorigin Do you think you can push your updates here?

**Comment by karelorigin** [comment]
Hey @fzipi! I've been super busy but I just pushed all the necessary changes, sorry about that.

**Review by fzipi — APPROVED** [review]
LGTM

**Pull request merged**
