### PR TITLE
Use chained end tag detection for rule 941310

### LINKED ISSUE #1942: Rule 941310: false positive for Russian letters "м" and "о"
### Description

I just enter a word from all the letters of the Russian alphabet and get a false positive.

* абвгдеёжзийклмнопрстуфхцчшщъыэюя – false positive
* абвгдеёжзийклнопрстуфхцчшщъыэюя – true negative
* абвгдеёжзийклмнпрстуфхцчшщъыэюя – true negative

I decided to check the whole alphabet after I started noticing problems with some Russian sentences. As it turned out, the problem is in specific letters

```
¼ = bc
¾ = be

м = d0 bc
о = d0 be
```

### Audit Logs / Triggered Rule Numbers

```
"response":{"body":"<html>\r\n<head><title>403 Forbidden</title></head>\r\n<body>\r\n<center><h1>403 Forbidden</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>\r\n","http_code":403,"headers":{"Server":"","Server":"","Date":"Fri, 04 Dec 2020 08:50:05 GMT","Content-Length":"146","Content-Type":"text/html","Access-Control-Allow-Origin":"*","Connection":"close","Access-Control-Allow-Credentials":"true","Strict-Transport-Security":"max-age=15724800; includeSubDomains"}},"producer":{"modsecurity":"ModSecurity v3.0.4 (Linux)","connector":"ModSecurity-nginx v1.0.1","secrules_engine":"Enabled","components":["OWASP_CRS/3.3.0\""]},"messages":[{"message":"US-ASCII Malformed Encoding XSS Filter - Attack Detected","details":{"match":"Matched \"Operator `Rx' with parameter `\\xbc[^\\xbe>]*[\\xbe>]|<[^\\xbe]*\\xbe' against variable `ARGS:json.description' (Value: `\\xd0\\xb0\\xd0\\xb1\\xd0\\xb2\\xd0\\xb3\\xd0\\xb4\\xd0\\xb5\\xd1\\x91\\xd0\\xb6\\xd0\\xb7\\xd0\\xb8\\xd0\\xb9\\xd0\\xba\\xd0 (156 characters omitted)' )","reference":"o27,5v17,64t:urlDecodeUni,t:lowercase,t:urlDecode,t:htmlEntityDecode,t:jsDecode","ruleId":"941310","file":"/etc/nginx/owasp-modsecurity-crs/rules/REQUEST-941-APPLICATION-ATTACK-XSS.conf","lineNumber":"527","data":"Matched Data: но found within ARGS:json.description: абвгдеёжзийклмнопрстуфхцчшщъыэюя","severity":"2","ver":"OWASP_CRS/3.3.0","rev":"","tags":["application-multi","language-multi","platform-tomcat","attack-xss","paranoia-level/1","OWASP_CRS","capec/1000/152/242"],"maturity":"0","accuracy":"0"}},{"message":"Inbound Anomaly Score Exceeded (Total Score: 5)","details":{"match":"Matched \"Operator `Ge' with parameter `5' against variable `TX:ANOMALY_SCORE' (Value: `5' )","reference":"","ruleId":"949110","file":"/etc/nginx/owasp-modsecurity-crs/rules/REQUEST-949-BLOCKING-EVALUATION.conf","lineNumber":"80","data":"","severity":"2","ver":"OWASP_CRS/3.3.0","rev":"","tags":["application-multi","language-multi","platform-multi","attack-generic"],"maturity":"0","accuracy":"0"}}]}
```

### Your Environment

* CRS version (e.g., v3.2.0): v3.3.0
* Paranoia level setting: 1
* ModSecurity version (e.g., 2.9.3): v3.0.4
* Image: k8s.gcr.io/ingress-nginx/controller:v0.41.2

### Confirmation

[X] I have removed any personal data (email addresses, IP addresses,
    passwords, domain names) from any logs posted.

### PR DESCRIPTION
**Pull request by theseion**
Reduce false positive detection by requiring both start and end tag
matches.

Added additional tests using characters from russion alphabet that
exhibit the same issues.

Fixes #1942

### CODE REVIEW

**Comment by franbuehler** [comment]
Thank you very much for this PR!! I'm currently trying to understand this again. I find these encoding issues so difficult. 

Could you please add a comment/explanation in the rule file and explain what the rule does and why it's a chained rule? So that we still have this explanation in the future, when we all forgot this issue here? This would be very helpful.

**Comment by theseion** [comment]
Yes, I'll do that. We can also get on a call together if you want. Might be easier than to figure it out yourself ;). Let me know.

**Comment by theseion** [comment]
I've added an explanation to the rule. Let me know whether it needs more information.

**Comment by franbuehler** [comment]
Thank you for the explanation and also for your offer for a call. I'll try again with this explanation and if it's still too complicated for me, I'll be happy to get back to your offer :)

**Comment by theseion** [comment]
I think I should add the false positive example using German umlauts to the test case. Would be nice to have one for the Russian characters too (I used the Russian bytes in the test but we don't have a complete example).

**Comment by dune73** [comment]
Thank you @theseion. Do you have time to join us on Monday for the monthly chat? We'll cover this PR there.

**Comment by theseion** [comment]
I do  but I don't have an owasp account, so I can't log in to Slack. Can you send me a Slack invitation? I think you have my e-mail address.

**Comment by dune73** [comment]
Sure thing. Here is the invitation. https://owasp-slack.herokuapp.com/

And here is the agenda: https://github.com/coreruleset/coreruleset/issues/2074

**Comment by franbuehler** [comment]
@franbuehler will setup a call with @theseion (next week).

**Comment by dune73** [comment]
Hey @franbuehler and @theseion. Any progress on this front? What came out of your call?

**Comment by theseion** [comment]
We haven't talked yet, so the review is still out.

**Comment by dune73** [comment]
Thanks for the info.

**Review by franbuehler — APPROVED** [review]
Max @theseion just explained the PR to me. Thanks for that! I understand the PR now!

It's actually quite simple: The current rule looks for an opening tag `<...>`. The chained rule now checks for a closing tag `</ ...>`.

One question remains: do we want to keep the rule at PL1?

Argument for PL1: the reported false positives are gone.

Argument for PL2: Only an incorrectly configured Tomcat has this vulnerability.

I would be for PL1. We can discuss that tonight. 

But this PR can be merged now. Thanks a lot!!

**Comment by dune73** [comment]
Thanks for sorting this out and the extensive documentation @theseion.

I get the feeling the only reason this rule is in PL1 is the fact that FPs are so rare. Given the very limited functionality of the rule (only tomcat configured for US-ASCII 7bit encoding) I can see this rule being shifted to PL3. Imagine running a rule that is hardly ever triggering because the attack is so rare...

**Comment by franbuehler** [comment]
Meeting decision July: https://github.com/coreruleset/coreruleset/issues/2141#issuecomment-874288876:
We leave it at PL1 and see if there are more FPs being reported in the future.

**Comment by dune73** [comment]
We forgot to merge this after the chat last month. Time to do this now.

**Pull request merged**
