### PR TITLE
Add PrestaShop config files to lfi

### PR DESCRIPTION
**Pull request by jf-viguier**
config/settings.inc.php is for PrestaShop 1.6- 
app/config/parameters.php for PrestaShop 1.7+

This files contain sensitive data: database access, private keys

### CODE REVIEW

**Comment by azurit** [comment]
@jf-viguier Thanks for this addition! First of the files is already included in `restricted-files.data`. Can you move the other one into `restricted-files.data`, too? Thanks.

**Comment by jf-viguier** [comment]
@azurit thanks for the review, I've moved the two lines in restricted-files.data. I can't find the first file with this path, So I added it two.

**Comment by dune73** [comment]
Hey @jf-viguier, thank you very much for your welcome contribution. Unfortunately, you are pushing a PR against the stale v3.3 branch.

We are currently working in the v4.0/dev branch. Can you rebase please?

In the v4.0 code base you will also find the setting @azurit mentioned, 3-4 lines above in the file. It's OK to remove that in favor of your code, also the comment line.

**Comment by jf-viguier** [comment]
@dune73 my bad.
I can't rebase because of a deleted commit.
I start a new PR

**Comment by jf-viguier** [comment]
@dune73 @azurit new PR here https://github.com/coreruleset/coreruleset/pull/3192 thanks

**Pull request closed without merging**
