### PR TITLE
Backports for 3.3.3

### PR DESCRIPTION
**Pull request by lifeforms**
This is the proposed PR for the 3.3.3 release.

### CODE REVIEW

**Comment by dune73** [comment]
* Copyright notice ought to be `2006-2022` (it's `2006-2020` now).
* 920610 and 920620 are still in the PR. We changed that meanwhile on v4.0/dev

**Comment by lifeforms** [comment]
That's correct:

- Updating the year is part of the release procedure and will happen at release.
- The backport PRs do not yet contain the 2 new PRs #2780 #2782 merged into 4.0 a few hours back. I will try backporting the 2 new changesets asap which is 13:00-15:00 CEST for me.

**Comment by dune73** [comment]
Copyright update: Thanks. I just noticed, we update the notice with a 2nd line actually.
```
# Copyright (c) 2021-2022 Core Rule Set project. All rights reserved.
```

That ought to be added by hand, is not it?

**Comment by lifeforms** [comment]
Thanks for fixing the tests @RedXanadu 🥳

**Pull request merged**
