### PR TITLE
fix(refactor): 942130 and 942131 regex-assembly

### PR DESCRIPTION
**Pull request by Xhoenix**
Fixes: #3846

### CODE REVIEW

**Review by fzipi — CHANGES_REQUESTED** [review]
The definition you made for `quotes-brackets` looks nice.

But taking a more holistic look, looks like everything is the same after the operator?

Moreover, we can probably use the regex-assembly postfix `##!$` with the whole rest of the line, right? We did use a prefix in https://github.com/coreruleset/coreruleset/blob/8ada24d68ea8fd51a49583585a7253a60d14b877/regex-assembly/942130.ra#L18 This would be a similar _postfix_:
```
##!$ [\s'\"`()]*?\b([\w]+)\b
```
... and remove all the occurrences on the single operators would make it more readable?

**Comment by Xhoenix** [comment]
Nice idea. This'll leave us with only the SQL operators and queries, leading to a much cleaner setup. Will do.

**Comment by Xhoenix** [comment]
LGTM!

**Review by fzipi — APPROVED** [review]
Now this looks way better. Thanks for the refactor.

**Pull request merged**
