### PR TITLE
fix(BB-53Y730TG): Add additional SQL function signatures

### PR DESCRIPTION
**Pull request by karelorigin**
This PR adds a bunch of SQLite signatures that get evaluated on >= PL2. Maybe we could also include some obvious ones such as `sqlite_compileoption_get` to the PL1 sibling?

### CODE REVIEW

**Comment by karelorigin** [comment]
This PR fixes https://github.com/coreruleset/coreruleset/issues/2882

**Comment by karelorigin** [comment]
This PR fixes https://github.com/coreruleset/coreruleset/issues/2828

**Comment by dune73** [comment]
Thank you for the links to the word lists. Yet using that word lists lead to redundancy with the function names starting with `abs` ...

I think this should be harmonized.

**Comment by dune73** [comment]
Suggestion to prevent the redundancy.

```
paths=("lang_corefunc.html" "lang_mathfunc.html" "lang_aggfunc.html"); declare items; for path in "${paths[@]}"; do items+=$(curl https://www.sqlite.org/$path -s | xmllint --html --xpath "//a[contains(@href,'func.html')]/text()" - 2>/dev/null | grep --color=never -Po "^[\w]+(?=\()"); done; echo "$items" | sort | uniq | while read FUNC; do egrep -q "^$FUNC$" 942150.data || echo "$FUNC"; done
```

**Comment by karelorigin** [comment]
I added a comment explaining the setup. From a coverage and maintenance perspective, the current approach makes the most sense.

**Comment by dune73** [comment]
OK with me. Thank you for the fix. Merging now.

**Pull request merged**
