### PR TITLE
Updated php-config-directives

### PR DESCRIPTION
**Pull request by gwen001**
Report: NFKUWKBD

Compared the current file to my php.ini (Ubuntu18.04, PHP8.1.5), I got some extra directives to add to `rules/php-config-directives.data`:

```
assert.exception
cgi.check_shebang_line
cgi.discard_path
cli_server.color
com.dotnet_version
curl.cainfo
enable_post_data_reading
engine
extension
ffi.enable
ffi.preload
imap.enable_insecure_rsh
input_encoding
internal_encoding
intl.use_exceptions
max_input_vars
mbstring.http_output_conv_mimetypes
mbstring.regex_retry_limit
mbstring.regex_stack_limit
mysqli.local_infile_directory
mysqli.rollback_on_cached_plink
mysqlnd.debug
mysqlnd.log_mask
mysqlnd.mempool_default_size
mysqlnd.net_read_timeout
mysqlnd.sha256_server_public_key
opcache.blacklist_filename
opcache.cache_id
opcache.consistency_checks
opcache.dups_fix
opcache.enable
opcache.enable_cli
opcache.enable_file_override
opcache.error_log
opcache.file_cache
opcache.file_cache_consistency_checks
opcache.file_cache_fallback
opcache.file_cache_only
opcache.file_update_protection
opcache.force_restart_timeout
opcache.huge_code_pages
opcache.interned_strings_buffer
opcache.lockfile_path
opcache.log_verbosity_level
opcache.max_accelerated_files
opcache.max_file_size
opcache.max_wasted_percentage
opcache.memory_consumption
opcache.mmap_base
opcache.optimization_level
opcache.opt_debug_level
opcache.preferred_memory_model
opcache.preload
opcache.preload_user
opcache.protect_memory
opcache.record_warnings
opcache.restrict_api
opcache.revalidate_freq
opcache.revalidate_path
opcache.save_comments
opcache.use_cwd
opcache.validate_permission
opcache.validate_root
opcache.validate_timestamps
openssl.cafile
openssl.capath
open_basedir
output_encoding
pcre.jit
precision
session.cookie_samesite
session.lazy_write
session.sid_bits_per_character
session.sid_length
session.trans_sid_hosts
session.trans_sid_tags
session.upload_progress.cleanup
session.upload_progress.enabled
session.upload_progress.freq
session.upload_progress.min_freq
session.upload_progress.name
session.upload_progress.prefix
session.use_strict_mode
SMTP
smtp_port
sqlite3.defensive
syslog.facility
syslog.filter
syslog.ident
sys_temp_dir
unserialize_max_depth
zend.assertions
zend.enable_gc
zend.exception_ignore_args
zend.exception_string_param_max_len
zend.multibyte
zend.script_encoding
zend_extension
```

### CODE REVIEW

**Comment by lifeforms** [comment]
Thanks for the submission!

I would remove `engine`, `extension`, `SMTP` and `precision` from the list as they are common words that will generate false alarms, e.g. when anybody talks about engines or precision in a text field.

**Comment by gwen001** [comment]
Done :)

**Comment by lifeforms** [comment]
@gwen001 My apologies, but our switch back to the v4.0/dev branch closed all the v4.1/dev PRs and it turns out it is impossible to reopen or rebase them! Could you send this PR again, but based on the v4.0/dev branch? My apologies!

**Comment by gwen001** [comment]
Done: https://github.com/coreruleset/coreruleset/pull/2560

**Pull request closed without merging**
