### PR TITLE
Rebase PR #1794

### PR DESCRIPTION
**Pull request by theMiddleBlue**
Please, see #1794

### CODE REVIEW

**Comment by theMiddleBlue** [comment]
tests are failing because of: 

- 942190-9: `from%2F%2A%2A%2Finformation_schema.%0A`
- 942190-19: `FROM%2F%2A%2A%2FINFORMATION_SCHEMA.%0A`
- 942190-31: `EXec%2F%2A%2A%2Fxp_cmdshell%0A`
- 942190-32: `FrOM%2F%2A%2A%2Finformation_schema.%0A`

since adding transformation function `t:removeCommentsChar` these tests may no more be useful. Can we remove them?

**Comment by fzipi** [comment]
Will review failure and comment.

**Review by fzipi — COMMENTED** [review]
Hey @theMiddleBlue ,

After reviewing, looks like we need to change the tests as you commented.

I'm still thinking on what we want to achieve, and if we really want to remove the tests or just modifying them to make a meaningful change.

For example, based on the `regexp-942190.data`, we want to match this:

**Comment by theMiddleBlue** [comment]
yep, updating those tests looks good to me. Should I do it in this PR with a new commit?

**Comment by fzipi** [comment]
Sounds perfect, sure!

**Comment by theMiddleBlue** [comment]
done. how does it look?

**Comment by fzipi** [comment]
Looks good to me!

**Pull request merged**
