### PR TITLE
feat(regexp-assemble): Merge data files for 930100

### PR DESCRIPTION
**Pull request by theseion**
Generating the regular expression for 930100 has required two files up
to now. With the improved regexp-assemble machinery the expression can
now be generated from a a single file.

### CODE REVIEW

**Comment by RedXanadu** [comment]
@theseion I'm having trouble testing this. I can't get `generate` to work:

```
$ ./regexp-assemble.py generate 930100
Traceback (most recent call last):
  File "/home/xanadu/.git/coreruleset/util/regexp-assemble/./regexp-assemble.py", line 229, in <module>
    namespace.func(namespace)
  File "/home/xanadu/.git/coreruleset/util/regexp-assemble/./regexp-assemble.py", line 127, in handle_generate
    context = create_context()
TypeError: create_context() missing 1 required positional argument: 'namespace'
```

Also, `update` is causing errors:

```
$ ./regexp-assemble.py update 930100
Traceback (most recent call last):
  File "/home/xanadu/.git/coreruleset/util/regexp-assemble/./regexp-assemble.py", line 229, in <module>
    namespace.func(namespace)
  File "/home/xanadu/.git/coreruleset/util/regexp-assemble/./regexp-assemble.py", line 146, in handle_update
    updater = Updater(create_context(namespace.rule_id))
  File "/home/xanadu/.git/coreruleset/util/regexp-assemble/./regexp-assemble.py", line 214, in create_context
    return Context(root_directory, namespace)
  File "/home/xanadu/.git/coreruleset/util/regexp-assemble/lib/context.py", line 17, in __init__
    self.single_rule_id = namespace.rule_id if namespace else None
AttributeError: 'str' object has no attribute 'rule_id'
```

But `compare` works, somehow?!

```
$ ./regexp-assemble.py compare 930100
Processing 930100, chain offset 0
Generating LALR tables
Regex of 930100 has changed!

===========
first difference
...
```

**Comment by theseion** [comment]
@RedXanadu Sorry, needed to rebase to get those fixes in. Thanks for reviewing!

**Comment by theseion** [comment]
That PR hasn't been merged: https://github.com/coreruleset/coreruleset/pull/2534. You'll have to wait or manually merge the two branches (of fix the error by hand ;) )

**Comment by RedXanadu** [comment]
Oh! I understand. Okay, I'll manually merge the branches and re-test this evening.

**Review by RedXanadu — APPROVED** [review]
Confirmed that the amended regexp-assemble data file results in the same regular expression pattern.

**Comment by RedXanadu** [comment]
@theseion I merged those branches together by hand and confirmed that it all works as intended.

The new preprocessor in `regexp-assemble` to make this work is very cool!

I'll leave it to you to merge this branch in whatever order you think is best, i.e. wait for https://github.com/coreruleset/coreruleset/pull/2534 to be merged first or not.

**Comment by theseion** [comment]
Thanks @RedXanadu!

**Pull request merged**
