### PR TITLE
Update for web-shells-php.data

### LINKED ISSUE #2630: update file `web-shells-php.data`
@azurit Do you think you can add documentation on where this list comes from, and how to update it?

### PR DESCRIPTION
**Pull request by azurit**
Fixes #2630.

### CODE REVIEW

**Comment by fzipi** [comment]
So...only documentation and no new webshells?

**Comment by fzipi360** [comment]
@azurit Maybe you didn't get this one. ☝️

**Comment by fzipi** [comment]
@azurit Maybe you didn't get this one. ☝️

**Comment by azurit** [comment]
I got it, i will look at it ASAP.

**Comment by fzipi** [comment]
Also, can we have a semi (or fully) automated to update this in the future? Like a combination of curl/awk/sed/etc ?

**Comment by azurit** [comment]
> Also, can we have a semi (or fully) automated to update this in the future? Like a combination of curl/awk/sed/etc ?

Hardly as, for every shell, you need to pick a part of the output which is unique enough. This is not a list of predefined keywords but unique patterns which needs to be choosed by hand.

**Comment by azurit** [comment]
Added 2 new shells. Didn't find more.

**Comment by dune73** [comment]
I do not see an automatic update with diverse sources as this either. But good findings.

**Comment by azurit** [comment]
@fzipi Check it now! :)

**Comment by fzipi** [comment]
Looks awesome now! Thanks for the detailed description!

**Pull request merged**
