### PR TITLE
feat(xss): add js methods to prevent xss

### PR DESCRIPTION
**Pull request by franbuehler**
This PR resolves BB finding 4A9UJH6G (issue #2661) by adding the missing js method `setTimeout()` by addind a new rule.
I also added the problematic methods `setInterval()` and `eval()` and the constructor `new Function()`, because I found them in the same context while researching the topic. 

2 open points to discuss:
* I'm not sure with `eval()` because it's already covered in 934100 and 933160. Do we need this in this new rule 941390?
* I added the new rule to PL1 which is maybe at too low PL. Maybe a higher PL would fit better?

And of course I added tests as well!

### CODE REVIEW

**Comment by franbuehler** [comment]
I'll fix the tests shortly.

**Comment by fzipi** [comment]
Is there any other method that we should be looking at? Maybe not in this one, but in a followup issue?

**Comment by franbuehler** [comment]
Very good input! According to Snyk the constructor `new Function()` is problematic too. 
https://snyk.io/blog/5-ways-to-prevent-code-injection-in-javascript-and-node-js/

I currently find only these 4 methods, but maybe there are others too.

**Review by fzipi — COMMENTED** [review]
This is a very nice rule now for unsafe JS! 💪 

One question about the transformations: do we need the `urlDecode` or is going to happen twice?

**Comment by franbuehler** [comment]
You're right! Nice finding. 

`urlDecode`: 

> ...The transformation function should not be used against variables that have already been URL-decoded (such as request parameters) unless it is your intention to perform URL decoding twice! ...

Since we're working on arguments already I can remove the `urlDecode`.

**Review by fzipi — APPROVED** [review]
LGTM now!

**Comment by lifeforms** [comment]
Great rule!

**Pull request merged**
