### PR TITLE
feat(lint): all rules must be updated

### PR DESCRIPTION
**Pull request by theseion**

### CODE REVIEW

**Comment by fzipi** [comment]
Oh, I understand now. Because I've committed directly based on your suggestions in the PR fixing this, then the update wasn't executed, so the actual rule differs from the data.

Do you want an additional PR for this, or just adding it here will do?

**Comment by theseion** [comment]
I'm working on a PR already. Ran into an issue though... 😢

**Review by fzipi — APPROVED** [review]
Finally!

**Comment by theseion** [comment]
Yes, indeed :) Thanks for the help!

**Pull request merged**
