### PR TITLE
fix: ignore checking compressed response body

### LINKED ISSUE #2751: FPs with rule 953120 for gzip data
### Description

I'm experiencing lots of FPs with rule `953120` for `Content-encoding: gzip` data. In all cases i analyzed, FPs were caused by these strings in gzip data:
```
<?\t
<?\r
```

I suggest following solutions:
1. Ceating sibling rule in PL2 for pattern `<\?\s+`.
2. Chaining rule which checks that `Content-encoding != gzip`. (Can we really trust it?)
3. Chaining rule which checks for gzip magic number in `RESPONSE_BODY`. (What about other encodings, for example Brotli?)

I'm voting for (1). I can send a PR for any.

### PR DESCRIPTION
**Pull request by azurit**
As we decided on last [monthy chat](https://github.com/coreruleset/coreruleset/issues/3694), we are going to trust `Content-Encoding` response header. This fix was supposed to deal only with rule `953120` but i think there no sense searching for any patterns in compressed data at all, so we should skip all rules dealing with `RESPONSE_BODY`. Current PR fixes this for 953* rules but i suggest to add similar skipping rule into all files with response rules (i can update this PR).

Fixes #2751.

### CODE REVIEW

**Comment by azurit** [comment]
Is [SecDisableBackendCompression](https://github.com/owasp-modsecurity/ModSecurity/wiki/Reference-Manual-(v2.x)) also updating/removing `Content-Encoding` header?

**Comment by azurit** [comment]
Just to be sure, i tested usage of `Content-Encoding` on Apache (should be also tested at least on nginx):
 - when a compression is activated on Apache level, RESPONSE_BODY is not compressed and header `Content-Encoding` is added after modsecurity (so modsec don't see it)
 - when a compression is activated on PHP level, RESPONSE_BODY is compressed and header `Content-Encoding` is visible to modsecurity

I can't test SecDisableBackendCompression though.

**Comment by fzipi** [comment]
What `SecDisableBackendCompression` does is just removing the `Accept-Encoding` and `TE` headers. See https://github.com/owasp-modsecurity/ModSecurity/blob/v2/master/apache2/mod_security2.c#L1114-L1117

**Comment by fzipi** [comment]
Note: because of how`libmodsecurity3` works, the exact same thing can be achieved by the connector itself. Meaning you can remove those headers in nginx for example before passing it to modsec3, and it should have the same effect.

**Review by fzipi — APPROVED** [review]
Yeah, it doesn't make sense to run this if content is compressed.

**Pull request merged**
