### PR TITLE
feat(ci): use relative paths in testing

### PR DESCRIPTION
**Pull request by fzipi**
Some improvements to the test pipeline:
- use relative paths, so when executing local tests would be easy to use
- provides artifacts when the build fails, so you can download the corresponding web server files
- switch to local container instead of using http://www.example.org as backend.

Changing to httpbin.org container has the side effect of returning 405 for one test so the url for the test needs to be fixed.

Signed-off-by: Felipe Zipitria <felipe.zipitria@owasp.org>

### CODE REVIEW

**Comment by fzipi** [comment]
After merging this one, the pipeline would get the logs as artifacts. Example:
```
=================================== FAILURES ===================================
/opt/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/ftw/testrunner.py:26: assert 200 == 405
==================== 1 failed, 202 passed in 70.71 seconds =====================

Error: Process completed with exit code 1.
Run actions/upload-artifact@v2
With the provided path, there will be 2 file(s) uploaded
Total size of all the files uploaded is 114759 bytes
Finished uploading artifact waf-logs. Reported size is 114759 bytes. There were 0 items that failed to upload
Artifact waf-logs has been successfully uploaded!
```

**Comment by dune73** [comment]
Is there a reason PARANOIA is set to 5?

**Comment by fzipi** [comment]
Yes, we want everything logged, in every paranoia level :)

**Comment by dune73** [comment]
And 4 would not do the job or are you looking to the future?

**Comment by fzipi** [comment]
You never know. But changing it, so we feel more in the present. :)

**Comment by dune73** [comment]
Thank you.

Actually mentioning a PL5 is like a micro aggression. It hints at me developing full whitelisting for all known HTTP headers in a future PL5. But that's probably my problem. :)

**Comment by dune73** [comment]
[Meeting decision monthly chat Jan 2020](https://github.com/coreruleset/coreruleset/issues/1953#issuecomment-754192936):

@franbuehler volunteered to review this.

**Review by franbuehler — APPROVED** [review]
I tested this PR and Felipe's branch also in my repo and it worked!
The tests all passed.
https://github.com/franbuehler/coreruleset/actions/runs/518401499

One question: Will this be a problem for us or just a warning? It has nothing to do with this PR. It's a known problem... But I still wanted to ask.

`
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.`

**Comment by dune73** [comment]
Thank you for this consolidation. Merging now.

**Comment by fzipi** [comment]
@franbuehler Well, that's a mess. We might have problems in a couple days.

**Pull request merged**
