### PR TITLE
Removed shell injection / XSS detection from 942260

### LINKED ISSUE #2355: Rewrite/rethink rule 942260 with re2 compatibility
### Motivation

Rule 942260 is using `++` and it is not supported.

```[\"'`]\s*?[^?\w\s=.,;)(]++\s*?[(@\"'`]*?\s*?\w+\W+\w```

We need to see if we can find a viable alternative or that can be dropped somehow.

### Proposed solution

None yet.

### PR DESCRIPTION
**Pull request by theseion**
Moved tests from 942260 to other rules, where it made sense

Fixes #2355.

### CODE REVIEW

**Comment by theseion** [comment]
The tests are covered as follows:
- 6: batch script? -> covered by multiple sqli rules, and also 941130
- 7-10: shell injection -> covered by 932105
- 11-14: exec on fs (sqlserver) -> covered by 942190
- 15-16: data dump (mysql) -> covered by 942480
- 17: batch script -> covered by 932115
- 18: XSS -> no real XSS payload, not detected
- 19: sql injection (mysql) -> covered by 942100-14
- 20: sql injection (sqlserver) -> covered by 942280
- 21: batch script -> covered by 941180
- 22: XSS -> covered by 941160

**Review by fzipi — APPROVED** [review]
Wow, I can believe it! This is awesome!

**Comment by theseion** [comment]
Sorry, a bit late, but I have a small addition to the PR. I've also removed matches for `find_in_set` and `union ... all`, since they are already covered by other rules:

find_in_set\s*?\( -> covered by 942150
union\s*?\s*?[([]*?\s*?select\s+
union\s*?all\s*?[([]*?\s*?select\s+
union\s*?distinct\s*?[([]*?\s*?select\s+
union\s*?[(!@]*?\s*?[([]*?\s*?select\s+ -> all covered by 942480

**Review by fzipi — APPROVED** [review]
If we keep removing, in 10 minutes the rule is gone. :D

**Comment by fzipi** [comment]
Double checked PLs, all good again.

**Pull request merged**
