### PR TITLE
fix(932200): detect windows style filepaths

### PR DESCRIPTION
**Pull request by s0md3v**
Issue: `U8Z0MSCP`

Description: The affected rule only works on *nix style filepaths.

Fix: Detect windows style filepaths by considering `\` as valid filepath delimiter like `/`.

### CODE REVIEW

**Comment by dune73** [comment]
### CRS Bug Bounty PR assessment

* **Rules affected** (list rules): FIXME
* **Paranoia Level addressed** (1, 2, 3, 4, full or explain): FIXME
* **FTW passes** (yes or no) : FIXME
* **Rule(s) picked for solution** (correct or not-correct or explain) : FIXME
* **Risk for false positives** (irrelevant, adequate, substantial or explain) : FIXME
* **Regular expression quality** (inspirational, decent base, needs work, adequate or explain) : FIXME
* **Documentation** (needs work, adequate or explain) : FIXME
* **Tests** (none or some or adequate) : FIXME
&nbsp;
* **Verdict** (Unusable, inspirational, usable, almost perfect or perfect) : FIXME

_This is not meant to be final. As a CRS dev, feel free to comment below and edit this form directly. As committer or observer, feel free to comment below with feedback and we will think about updating the assessment accordingly._

**Comment by RedXanadu** [comment]
@s0md3v Your new test doesn't seem to be working at the moment.

**Comment by lifeforms** [comment]
We have a rule for backslash notation in the contribution guidelines: `\\`-> `\x5c`
Please if possible could you put it after the `/`.

We need also a test for the backslash, some more tests could really help.

**Comment by fzipi** [comment]
Can you also be sure that your PR doesn't change permissions on files? I see a change from 644 to 755 (probably because of WSL?).

**Comment by lifeforms** [comment]
Oops. Seems that the test is failing. Is the test wrong or does the rule have a problem? Could you have a look at that @s0md3v ?

**Comment by fzipi** [comment]
I'm struggling to make the test match. Will enter debug mode.

**Comment by RedXanadu** [comment]
I believe the proposal here changes the existing regular expression in ways that fundamentally change its meaning. I think this needs a closer inspection.

**Comment by lifeforms** [comment]
This issue may be harder than it looks (or maybe not). I am confused because as far as I know, we should have detected this technique also in earlier releases. So I think we may have to fix an existin rule as well, and that rule is really complex. I will close this for now, and use it as a reference.

**Pull request closed without merging**
