### PR TITLE
Fix bypass 942190

### PR DESCRIPTION
**Pull request by theMiddleBlue**
Referring to #1727 this should fix the bypass using comment char+new line.

### CODE REVIEW

**Comment by theMiddleBlue** [comment]
working on test error...

**Comment by dune73** [comment]
This needs to be rebased and then there are probably still the errors above. Any progress @theMiddleBlue?

**Comment by lifeforms** [comment]
TODO from meeting:

- theMiddleBlue will look at the test failure.

**Comment by theMiddleBlue** [comment]
rebased at #1910

**Pull request closed without merging**
