### PR TITLE
fix(tests): make find_marker more resilient

### PR DESCRIPTION
**Pull request by theseion**
When finding the X-CRS-Test marker, look back three lines instead of
just one. If the anomaly scoring rules trigger for some reason, they
will also appear in the log and hide the test marker.

Also add `charset=utf-8` to the marker request to guard agains other
rules triggering, which would mess with their tests.

### CODE REVIEW

**Comment by theseion** [comment]
I don't get why the tests fail. Works on my machine...

**Comment by fzipi** [comment]
Is this strictly pre-bb-merge?

**Comment by theseion** [comment]
No. I've removed the label.

**Comment by theseion** [comment]
I don't know why the anomaly rules triggered in my case, but they don't anymore. If the rules aren't triggered, the change in this PR will actually make tests fail. 

Closing this. Sorry for the fuss @fzipi.

**Pull request closed without merging**
