### PR TITLE
feat: check if rule use TX:N target without capture action

### PR DESCRIPTION
**Pull request by airween**
Solves #3764.

### CODE REVIEW

**Review by fzipi — APPROVED** [review]
The code _looks_ good.

I think we should move the utils out of this repo. We cannot test them properly, and they are related but they could be siblings to other major tools like ftw or the toolchain. Maybe having a linting tool that we can use as an action?

**Comment by fzipi** [comment]
BTW, with this one applied there are no issues with the rules code, right?

**Comment by airween** [comment]
> BTW, with this one applied there are no issues with the rules code, right?

Yes, there isn't any issue regarding the rules.

**Comment by airween** [comment]
> The code _looks_ good.
> 
> I think we should move the utils out of this repo. We cannot test them properly, and they are related but they could be siblings to other major tools like ftw or the toolchain. Maybe having a linting tool that we can use as an action?

It's up to us - btw I usually used to use this tool after all modification and it helps me a lot. I mean it's comfortable that I can run from the same place as the rules are. But we can move that to a standalone repository (when I started to work on it that was the plan - this is why I created a CHANGLOG inside the directory)

**Pull request merged**
