### PR TITLE
add burpcollaborator to scanner user agents

### PR DESCRIPTION
**Pull request by amirhoseinaliakbarian**
Adding burpcollaborator as an scanner.

### CODE REVIEW

**Comment by azurit** [comment]
Thank you very much!

Can you please:
 - fix alphabetical ordering
 - add an example of `User-Agent` into comments
 - add homepage URL into comments (if there's any)
?

**Comment by amirhoseinaliakbarian** [comment]
I have fixed what you ask.

**Review by azurit — APPROVED** [review]
Looks good!

**Comment by dune73** [comment]
Thank you @amirhoseinaliakbarian for this welcome contribution and @azurit for the constructive feedback.

Merging now.

**Pull request merged**
