### PR TITLE
fix(942190): Add 'except (select|values)' to auth bypasses

### PR DESCRIPTION
**Pull request by terjanq**
This is a patch for a bypass from the BugBounty event.

**Report id:** `LNAYL9MM`

### Bypass payloads:
  * `email=admin@juice-sh.op'except select ""a,2,3,4,5,6,7,8,9,10,11,12,13--`

### Alternative payloads:
  * `email=admin@juice-sh.op'except values(1,2,3,4,5,6,7,8,9,10,11,12,13)--`
  
### Explanation:
SQLite [except](https://www.sqlite.org/syntax/compound-operator.html) compound operator can be used to bypass authentication, and in rarer scenarios potentially be used to gather information. The full language tree can be found [here](https://www.sqlite.org/syntax/compound-operator.html). After the `except` keyword, only `select` or `values` may occur, whereas after the `values` a left parenthesis (`(`) must be present which is included in the expression to limit false-positives. 

### Fix caveats
I didn't find fix caveats. The rule is generalized, but [shouldn't](https://www.google.com/search?q=%22except+select%22+-sql+-sequel+-from) yield many if any false-positives because `except select` seems to not be a valid grammar construction.

### CODE REVIEW

**Comment by azurit** [comment]
Hi @terjanq, thanks for sending this!

**Comment by terjanq** [comment]
Converting to draft as I will be adding this testcase to #2568

**Comment by terjanq** [comment]
Converting to draft as I will be adding this testcase to #2568

**Comment by terjanq** [comment]
Leaving the rule here as it fits better the context of 942190 than the new rule 942520 from #2568

**Comment by dune73** [comment]
### CRS Bug Bounty PR assessment

* **Rules affected** (list rules): FIXME
* **Paranoia Level addressed** (1, 2, 3, 4, full or explain): FIXME
* **FTW passes** (yes or no) : FIXME
* **Rule(s) picked for solution** (correct or not-correct or explain) : FIXME
* **Risk for false positives** (irrelevant, adequate, substantial or explain) : FIXME
* **Regular expression quality** (inspirational, decent base, needs work, adequate or explain) : FIXME
* **Documentation** (needs work, adequate or explain) : FIXME
* **Tests** (none or some or adequate) : FIXME
&nbsp;
* **Verdict** (Unusable, inspirational, usable, almost perfect or perfect) : FIXME

_This is not meant to be final. As a CRS dev, feel free to comment below and edit this form directly. As committer or observer, feel free to comment below with feedback and we will think about updating the assessment accordingly._

**Pull request merged**
