### PR TITLE
docs: final changes to CHANGES.md before v4

### PR DESCRIPTION
**Pull request by dune73**
Let's keep this PR open until we're done with changes.

Plus review now and comment accordingly so issues can be sorted out.

For the record: This is how to sort the changes in the direct rule impact section:

`sed -e "s/\(9[0-9][0-9][0-9x][0-9x][0-9x]\)\(.*\)/\1\2\1/" -e "s/\]$/]000000/" -e "s/xxx$/000/" -e "s/\(.*\)\(......\)$/\2\1/" | sort -n | sed -e "s/^......//"`

### CODE REVIEW

**Comment by dune73** [comment]
Thanks for the fix @RedXanadu

**Comment by fzipi** [comment]
@dune73 @RedXanadu We should sort the changes. There are way too many, and `chore`, `fixes` and `feat` are intertwined making it difficult to read. We should apply alphabetical sort here. And probably showing first `feat`ures, then `fix`es, and lastly `chores` and `test`.

**Comment by dune73** [comment]
I followed

* topical sort for the big changes
* alphabetical sort for the changes not impacting any rules
* sort by first ruleid in PR for the changes impacting rules (as indicated in the file, also see above)

I know it's not easy to read. But it's mostly OK to go from rule to rule now. And I think this is the preferred way on consuming these changes.

But I am happy to apply a different sort order if you think that's better.

**Comment by dune73** [comment]
U OK with the sort order now, @fzipi?

**Comment by fzipi** [comment]
Yes, we can go out with this one.

**Comment by dune73** [comment]
Cool. The CHANGES.md in this PR is now up to date with latest changes. Feel free to merge.

**Review by fzipi — APPROVED** [review]
LGTM

**Pull request merged**
