### PR TITLE
docs: Update and tidy CHANGES.md file for v4.0 release

### PR DESCRIPTION
**Pull request by RedXanadu**
This will partially_resolve #3538 once the updates are complete.

### CODE REVIEW

**Comment by theseion** [comment]
@RedXanadu I think we're done...?

**Comment by RedXanadu** [comment]
@theseion I can check and approve later this afternoon :grinning:

**Comment by RedXanadu** [comment]
@theseion I've just read the bits you've done and I'm happy.

If you're happy, can you approve and merge, please? :smile:

**Comment by theseion** [comment]
Then we're all happy ;)

**Review by theseion — APPROVED** [review]

**Pull request merged**
