### PR TITLE
feat: added new webshells and tests (955100 PL1) (Jozef Sudolski)

### PR DESCRIPTION
**Pull request by azurit**
Adding new web shell.

### CODE REVIEW

**Comment by azurit** [comment]
changelog comment:

feat: New (unknown) web shell (Jozef Sudolsky)

**Comment by dune73** [comment]
Merging as soon as @azurit provides the tests (promised via DM).

**Comment by azurit** [comment]
Unfortunately, i don't know why are my tests failing.

**Comment by azurit** [comment]
@dune73 Done.

**Review by dune73 — APPROVED** [review]

**Pull request merged**
