### PR TITLE
fix: adding more missing tags and ver actions

### PR DESCRIPTION
**Pull request by azurit**
- Adding missing tag `OWASP_CRS` to everywhere.
 - Adding missing `ver` action to everywhere.
 - Reordering tags in some rules to unify tag order.

### CODE REVIEW

**Review by dune73 — APPROVED** [review]

**Comment by dune73** [comment]
Thank you for the PR.

This looks good, but I did not check the completeness nor the details of the change.

**Comment by theseion** [comment]
What's the rationale for reordering? I can't find any pattern that makes sense to me, it's not alphabetical, at least.

**Comment by azurit** [comment]
> What's the rationale for reordering? I can't find any pattern that makes sense to me, it's not alphabetical, at least.

@theseion I reordered only `paranoia-level/*` and `PCI/*` tags to match the order which most rules are using:
```
tag:'paranoia-level/*',\
tag:'OWASP_CRS',\
tag:'capec/*',\
tag:'PCI/*',\
```

**Comment by theseion** [comment]
Makes sense. Maybe we should follow up with a PR for canonical tag ordering (e.g., alphabetical).

**Comment by azurit** [comment]
Not sure if alphabetical ordering is the right one for tags but we definitely should give some guidence for this.

**Comment by airween** [comment]
> @theseion I reordered only `paranoia-level/*` and `PCI/*` tags to match the order which most rules are using (now all):

do we want to check the correct order in CI pipeline with our [crs-rule-check](https://github.com/coreruleset/coreruleset/tree/main/util/crs-rules-check)? (If yes, we need to define the rule which describes the order.)

For the PR: why do we want to add `OWASP-CRS` tag to **every** rule? I mean to admin rules too...

**Comment by theseion** [comment]
>do we want to check the correct order in CI pipeline with our [crs-rule-check](https://github.com/coreruleset/coreruleset/tree/main/util/crs-rules-check)? (If yes, we need to define the rule which describes the order.)

Yes, I would. But first we need to agree on the ordering mechanism.

> For the PR: why do we want to add OWASP-CRS tag to every rule? I mean to admin rules too...

That was part of the discussion in the last chat. If you disable by tag you should assume that you disable everything. The "admin" rules don't make sense without the rest IMO and it's actually strange that they would remain enabled when I've disabled "all CRS rules".

**Comment by azurit** [comment]
Is this suitable for merging?

**Comment by theseion** [comment]
I think so, yes.

**Pull request merged**
