### PR TITLE
Stop decoding things twice

### LINKED ISSUE #1616: Revert #578
_Issue for tracking original pull request created by user fgsch on date 2019-10-31 07:47:00.
            Link to original PR: https://github.com/SpiderLabs/owasp-modsecurity-crs/pull/1616._

HEAD is: c67ed8bc40c6579b95536655b9c121be4246df38
BASE is: e0bea233b72e62f2c441573ff03cb87ace7a1e70
Stop decoding things twice. See #590 for details.

### PR DESCRIPTION
**Pull request by fgsch**
Fixes #1616.

### CODE REVIEW

**Review by franbuehler — APPROVED** [review]
LGTM and can be merged.

**Comment by franbuehler** [comment]
Monthly chat meeting September: https://github.com/coreruleset/coreruleset/issues/1869#issuecomment-688474359.
@fgsch adds more information. Then this PR can be merged.

**Comment by lifeforms** [comment]
TODO from meeting:

- add more information
- rebase for conflicts in rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf

Moved to next meeting!

**Comment by dune73** [comment]
OK. This has been open long enough. Merging now. Thank you for making this change @fgsch.

**Comment by fgsch** [comment]
Sorry, I am planning to add a longer explanation this week. 
If you don't mind waiting another week it'd be great.

**Comment by dune73** [comment]
OK. Let's keep it pending then. A description is indeed welcome, (but I did not think you would submit one :) ).

**Comment by dune73** [comment]
Nevermind. I added a bit of description and merged at last.

**Pull request merged**
