### PR TITLE
ci: add PR template example

### PR DESCRIPTION
**Pull request by fzipi**
Signed-off-by: Felipe Zipitria <felipe.zipitria@owasp.org>

Proposal for PR template.

### CODE REVIEW

**Comment by dune73** [comment]
Thank you @fzipi. This is very welcome and it is true, that our PRs are often a bit thin on explanations. This will improve the situation, I am sure.

Let's talk about this at the CRS meeting, but this is ready from my point of view.

**Comment by RedXanadu** [comment]
A couple of questions:

"Linting is correct"
What is being checked for, in this step? I'm not 100% sure what linting means in this context.

"YAML tests look good and data is sane"
How is the YAML to be checked?

Apologies if these are really basic questions, but I'm not sure how to check these off (and maybe some other people would be confused on how to complete a review using the new checklist).

**Comment by airween** [comment]
I ran into these issues, so based on my experiences:

> "Linting is correct" What is being checked for, in this step? I'm not 100% sure what linting means in this context.

I think you can use [this](https://github.com/fernandrone/linelint.git) tool to check the README files, eg:

```
git clone https://github.com/fernandrone/linelint.git
go build
./linelint /path/to/coreruleset/ANY/DIR/README.md
```

> "YAML tests look good and data is sane" How is the YAML to be checked?

this was my way:

```
sudo apt install yamllint
yamllint -c .yamllint.yml tests/regression/tests/
```

> Apologies if these are really basic questions, but I'm not sure how to check these off (and maybe some other people would be confused on how to complete a review using the new checklist, too).

no worries, these were very new info for me too :). Hope this helps.

**Comment by fzipi** [comment]
@RedXanadu Is there something additional oyu think we need to add. Maybe rephrase something?

**Comment by RedXanadu** [comment]
@fzipi I wonder if we need to document the review procedure somewhere?

For a new developer coming onboard, it would be good if we had something that they could read to explain _exactly what_ they need to do to review a PR. It doesn't need to be long, maybe just something in a few clear, simple action points of "Do A, then Do B, then Do C"?

**Comment by dune73** [comment]
We agreed to write a checklist for PR reviews.

https://github.com/coreruleset/coreruleset/wiki/DevRetreat21AvoidCVEs

**Comment by RedXanadu** [comment]
Yes: “[the] checklist should be made into a set of public guidelines to incentivise contributions, so that new contributors would have a clear idea of how to write good commits that would be more likely to be accepted.”

I think that is the part missing, at the moment.

**Comment by RedXanadu** [comment]
That seems much clearer :) I think most people should be able to understand how to review a PR based on that checklist (although maybe we need guidance elsewhere (separate from this PR) about how to test for a ReDoS vulnerability?).

**Comment by fzipi** [comment]
@RedXanadu Started page https://github.com/coreruleset/coreruleset/wiki/Testing-for-Regular-Expresion-DoS for testing ReDoS. I think we can merge this one now, while we complete the documentation on the wiki.

**Comment by RedXanadu** [comment]
@fzipi Amazing.

Other people have already said this PR looks good to go… And now we have the start of awesome documentation, too, so it is 100% good to go, I think!

Merging now.

**Pull request merged**
