### PR TITLE
Remove RE packages and DoS rules (move to plugins)

### PR DESCRIPTION
**Pull request by RedXanadu**
PR removes the rule exclusion package files (rules/REQUEST-903*) and DoS rules file (rules/REQUEST-912-DOS-PROTECTION.conf), all of which are being moved out of the core CRS and in to plugins for the next milestone CRS release (4.0).

### CODE REVIEW

**Comment by azurit** [comment]
Don't forget to clean `crs-setup.conf.example`.

**Comment by RedXanadu** [comment]
I hadn't realised that would need to be done. There's quite a lot of work involved in picking that all apart… I thought it would be simpler :smile: 

I'll re-assess before a PR.

**Comment by azurit** [comment]
Maybe i can look at it instead of you, just tell.

**Comment by RedXanadu** [comment]
Okay, this took some time to unpick…

Also, there was a merge conflict, which I think I successfully resolved.

I believe this PR is now complete and removes the rule exclusion package files (rules/REQUEST-903*) and DoS rules file (rules/REQUEST-912-DOS-PROTECTION.conf) **and** the references to them.

**Comment by azurit** [comment]
Looks good (except the conflicts)!

**Review by azurit — APPROVED** [review]

**Comment by RedXanadu** [comment]
Arrrrrgh, I don't understand, I spent time resolving the conflicts yesterday.

How are there new conflicts overnight?!

**Comment by fzipi** [comment]
I think the conflicts are because you removed files only?

**Comment by RedXanadu** [comment]
To finish the conversation: PR #2481 caused the merge conflicts. A rebase resolved them.

Merging now, following approval.

**Pull request merged**
