### PR TITLE
Add method "SEARCH" to allowed method

### PR DESCRIPTION
**Pull request by ignatiev**
I found  method SEARCH used in Photos

### CODE REVIEW

**Comment by lifeforms** [comment]
Thanks so much for this contribution! We'd like to accept and merge it.

Could you however rebase the commit on our new development branch `v3.4/dev`?

The old one that you used, `v3.3/dev` is no longer in active development.

If you can't figure it out how to rebase this with Git, I won't blame you, I'd recommend just creating a simple new PR.

**Comment by fzipi** [comment]
@ignatiev If you are around, can you do the rebase? We are interested in merging this one :)

**Comment by ignatiev** [comment]
I did rebase for the first time. I hope I did it right

**Comment by fzipi** [comment]
This looks good, thanks!

Merging.

**Pull request merged**
