### PR TITLE
fix#2119

### PR DESCRIPTION
**Pull request by NiceYouKnow**
Add a new rule for 942380：
\bexists\s*?\(\s*?select\b

Add a t:lowercase for 942380,because the rules generated by the data file are case-sensitive, but we all know that SQL statements are not case-sensitive.

### CODE REVIEW

**Comment by NiceYouKnow** [comment]
@franbuehler  Please check my PR, thank you!

**Comment by franbuehler** [comment]
You found another problem here: the missing ignore case flag. Thank you!!
In the other rules we added an ignore case flag. You can have a look at this rule here:
https://github.com/coreruleset/coreruleset/blob/v3.4/dev/rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf#L149

I think it would make sense to do it the same way here, so that we are consistent.

What do you think?

And @theseion , would you also like to take a look at this PR here?

**Comment by NiceYouKnow** [comment]
Hi, @franbuehler your idea is right, I will update the rules.

**Review by theseion — APPROVED** [review]
Great catch!
Looks good to me. +1 for adding the comment about the additional flag.

**Review by franbuehler — APPROVED** [review]

**Comment by franbuehler** [comment]
Ready to be merged. Thank you!!

**Comment by dune73** [comment]
Very nice. Many, many thanks @NiceYouKnow. Merging now.

**Pull request merged**
