### PR TITLE
Override modsec rule 200001

### PR DESCRIPTION
**Pull request by theMiddleBlue**
referring to #1315 this rule override 200001 and set BodyProcessor to JSON in order to work as expected with the following CT:

https://regex101.com/r/3AvnWp/1
```
application/activity+json
application/alto-costmap+json
application/alto-costmapfilter+json
application/alto-directory+json
application/alto-endpointcost+json
application/alto-endpointcostparams+json
application/alto-endpointprop+json
application/alto-endpointpropparams+json
application/alto-error+json
application/alto-networkmap+json
application/alto-networkmapfilter+json
application/alto-updatestreamcontrol+json
application/alto-updatestreamparams+json
application/atsc-rdt+json
application/calendar+json
application/captive+json
application/coap-group+json
application/csvm+json
application/dicom+json
application/dns+json
application/elm+json
application/expect-ct-report+json
application/fhir+json
application/geo+json
application/jf2feed+json
application/jose+json
application/jrd+json
application/jscalendar+json
application/json
application/json-patch+json
application/jwk+json
application/jwk-set+json
application/ld+json
application/merge-patch+json
application/mud+json
application/ppsp-tracker+json
application/problem+json
application/pvd+json
application/rdap+json
application/reputon+json
application/sarif+json
application/scim+json
application/senml+json
application/senml-etch+json
application/sensml+json
application/stix+json
application/taxii+json
application/td+json
application/tlsrpt+json
application/vcard+json
application/vnd.amadeus+json
application/vnd.apache.thrift.json
application/vnd.api+json
application/vnd.aplextor.warrp+json
application/vnd.apothekende.reservation+json
application/vnd.artisan+json
application/vnd.avalon+json
application/vnd.bbf.usp.msg+json
application/vnd.bekitzur-stech+json
application/vnd.byu.uapi+json
application/vnd.capasystems-pg+json
application/vnd.collection+json
application/vnd.collection.doc+json
application/vnd.collection.next+json
application/vnd.coreos.ignition+json
application/vnd.cryptii.pipe+json
application/vnd.cyclonedx+json
application/vnd.datapackage+json
application/vnd.dataresource+json
application/vnd.document+json
application/vnd.drive+json
application/vnd.futoin+json
application/vnd.gentics.grd+json
application/vnd.geo+json
application/vnd.hal+json
application/vnd.hc+json
application/vnd.heroku+json
application/vnd.hyper+json
application/vnd.hyper-item+json
application/vnd.hyperdrive+json
application/vnd.ims.lis.v2.result+json
application/vnd.ims.lti.v2.toolconsumerprofile+json
application/vnd.ims.lti.v2.toolproxy+json
application/vnd.ims.lti.v2.toolproxy.id+json
application/vnd.ims.lti.v2.toolsettings+json
application/vnd.ims.lti.v2.toolsettings.simple+json
application/vnd.las.las+json
application/vnd.leap+json
application/vnd.mason+json
application/vnd.micro+json
application/vnd.miele+json
application/vnd.nearst.inv+json
application/vnd.oci.image.manifest.v1+json
application/vnd.oftn.l10n+json
application/vnd.oma.lwm2m+json
application/vnd.oracle.resource+json
application/vnd.pagerduty+json
application/vnd.restful+json
application/vnd.seis+json
application/vnd.shootproof+json
application/vnd.shopkick+json
application/vnd.siren+json
application/vnd.tableschema+json
application/vnd.think-cell.ppttc+json
application/vnd.vel+json
application/vnd.xacml+json
application/voucher-cms+json
application/webpush-options+json
application/yang-data+json
application/yang-patch+json
application/hal+json
```

### CODE REVIEW

**Comment by theMiddleBlue** [comment]
```
Syntax invalid: {'Error': 'Syntax error in line 359 col 30: Expected \'text/xml\' or \'text/json\' or \'URLENCODED\' at position /home/runner/work/coreruleset/coreruleset/rules/REQUEST-901-INITIALIZATION.conf:(359, 30) => \'Processor=*JSON"   # \'.'}
```

doesn't make sense to me, any idea of why "Check CRS Syntax" fails?

**Comment by fzipi** [comment]
Let me check that one.

**Comment by fzipi** [comment]
Now it is working!

**Comment by theMiddleBlue** [comment]
thanks @fzipi !

**Comment by dune73** [comment]
Oh, oh. I often wondered if JSON CT was so simple. :)

Did you try to submit this to the ModSecurity project first?

Apparently there is also a problem with the way 200005 is being used / recommended to be included. If they do not want to upgrade 200001 based on your proposal it may be worthwhile to consider to replace the recommended stuff with our own approach completely midterm.

**Comment by franbuehler** [comment]
Meeting decision April 5th (https://github.com/coreruleset/coreruleset/issues/2051#issuecomment-813570935): @dune73 will take this over and work with @theMiddleBlue to get it merged.

**Comment by dune73** [comment]
I have formally asked ModSec to update their recommended rule 200001: [Issue 2564](https://github.com/SpiderLabs/ModSecurity/issues/2564)

Let's wait for a few days before we merge.

Also: where do you have that huge list from?

**Comment by theMiddleBlue** [comment]
Thanks!

I got the list from IANA with:
```sh
curl -s 'https://www.iana.org/assignments/media-types/application.csv' | grep json | awk 'BEGIN{FS=","}{print $2}'
```

**Comment by theMiddleBlue** [comment]
P.S.

IANA doesn't include `application/hal+json` used by Drupal (IDK why...) I've added it manually

**Comment by dune73** [comment]
Thank you beautiful use of AWK. I'd just use cut/sed as my hammer of choice ...

**Comment by dune73** [comment]
What is a bit disturbing are entries like "application/vnd.miele+json". That's my washing machine and I do not want it to talk over the internet.

**Comment by theMiddleBlue** [comment]
hmmm your washing machine has an HTTP client? that's interesting :) btw I think that the 200001 purposes should be "use the right body processor and avoid false negative/positive" from anywhere to the protected webapp. Maybe that list includes some "response-only" content-type?

**Comment by dune73** [comment]
Actually, my washing machine does not. But the salesperson told me 2 years ago it's the last generation of washing machines without WIFI. And I am quite sure a washing machine with WIFI will have libcurl on board to ring home and say hello. Apparently with JSON. 

I agree it could be response-only, but I seriously doubt that.

**Comment by theMiddleBlue** [comment]
is there any news from modsecurity? If I understood well they add a brand new rule (200006) that extends the original one (200001). Are we ok with it?

**Comment by dune73** [comment]
The ModSec guys are reluctant to expand the existing rule 200001, so they added this in comments and think about making it a new rule in 200006. They are asking for more feedback and I think we should provide that.

https://github.com/SpiderLabs/ModSecurity/pull/2586

**Comment by franbuehler** [comment]
[Meeting decision August 2021](https://github.com/coreruleset/coreruleset/issues/2169#issuecomment-891255600): we will wait with merging this PR and maybe take this as a topic for the dev hackweek.

**Comment by dune73** [comment]
We talked about the bigger problem around this at the dev retreat in October 2021. Notes at https://github.com/coreruleset/coreruleset/wiki/DevRetreat21ModSecRecommendedRules

So a fix would also be part of a bigger PR.

OK if we close this, @theMiddleBlue?

**Comment by theMiddleBlue** [comment]
Yes, thanks!

**Pull request closed without merging**
