### PR TITLE
Fix: Typos across the entire project as reported by codespell

### LINKED ISSUE #2518: Typos: Codespell report for v4-RC1
https://fossies.org/linux/www/coreruleset-4.0.0-rc1.tar.gz/codespell.html

### PR DESCRIPTION
**Pull request by airween**
Fixes #2518

### CODE REVIEW

**Comment by dune73** [comment]
Thank you for this quick fix.

Changed the title of the PR to be in line with the _conventional commit_ idea.

**Comment by dune73** [comment]
Looked through all the fixes. Looks good. Merging now.

**Comment by Kkaungmyat** [comment]
gh pr checkout 60

**Comment by Kkaungmyat** [comment]
> ပြင်ဆင်မှုများ #2518

Porn japan

**Pull request merged**
