### PR TITLE
Added some files in LFI restricted list

### PR DESCRIPTION
**Pull request by gwen001**
Reports: C4AKMJX5 , ZITHAVYB , EH5C5EUO

(from real tests on production servers)

```
etc/subuid
etc/subuid-
etc/subgid
etc/subgid-
etc/gshadow
etc/gshadow-
etc/system-release-cpe
etc/centos-release-upstream
etc/scw-release
etc/freshclam.conf
etc/mongod.conf
etc/nuxeo.conf
usr/lib/rpm/rpm.log
var/log/yum.log
var/log/freshclam.log
var/log/logstash/logstash-plain.log
var/log/logstash/logstash-slowlog-plain.log
```

I also identified some directories but looks like you try to avoid that so currently reviewing the list, thanks :)

### CODE REVIEW

**Comment by lifeforms** [comment]
Thanks!

I think it would be fine to add the `var/log` directory because any file in that directory should be considered private and I think the risk of false alerts is low.

We can keep the files under `var/log` in the blocklist because a more specific request is useful to have logged.

**Comment by lifeforms** [comment]
Sounds great. I think due to preprocessing, the `/` characters at the start/end of the string will be removed before we check it, so I would add them like: `etc/ansible`

**Comment by dune73** [comment]
Here is an alternative list:

```
etc/acpi
etc/alsa
etc/alternatives
etc/apache2
etc/apm
etc/apparmor
etc/apparmor.d
etc/apport
etc/apt
etc/asciidoc
etc/avahi
etc/bash_completion.d
etc/binfmt.d
etc/bluetooth
etc/bonobo-activation
etc/brltty
etc/ca-certificates
etc/calendar
etc/chatscripts
etc/chromium-browser
etc/clamav
etc/cni
etc/console-setup
etc/coraza-waf
etc/cracklib
etc/cron.d
etc/cron.daily
etc/cron.hourly
etc/cron.monthly
etc/cron.weekly
etc/cups
etc/cupshelpers
etc/cups.save
etc/dbus-1
etc/dconf
etc/default
etc/depmod.d
etc/dhcp
etc/dictionaries-common
etc/dkms
etc/dnsmasq.d
etc/dockeretc/dpkg
etc/emacs
etc/environment.d
etc/fail2ban
etc/firebird
etc/firefox
etc/fonts
etc/fwupd
etc/gconf
etc/gdb
etc/gdm3
etc/geoclue
etc/ghostscript
etc/gimp
etc/glvnd
etc/gnome
etc/gnome-vfs-2.0
etc/gnucash
etc/GNUstep
etc/groff
etc/grub.d
etc/gss
etc/gtk-2.0
etc/gtk-3.0
etc/hp
etc/ifplugd
etc/ImageMagick-6
etc/init
etc/init.d
etc/initramfs-tools
etc/insserv.conf.d
etc/iproute2
etc/iptables
etc/.java
etc/java
etc/java-11-openjdk
etc/java-17-oracle
etc/java-8-openjdk
etc/kernel
etc/ldap
etc/ld.so.conf.d
etc/libblockdev
etc/libibverbs.d
etc/libnl-3
etc/libpaper.d
etc/libreoffice
etc/lighttpd
etc/logcheck
etc/logrotate.d
etc/lynx
etc/mail
etc/mc
etc/menu
etc/menu-methods
etc/modprobe.d
etc/modsecurity
etc/modules-load.d
etc/monit
etc/mono
etc/mplayer
etc/mpv
etc/Muttrc.d
etc/mysql
etc/netplan
etc/network
etc/networkd-dispatcher
etc/NetworkManager
etc/newt
etc/nghttpx
etc/nikto
etc/ODBCDataSources
etc/openal
etc/openmpi
etc/opt
etc/osync
etc/PackageKit
etc/pam.d
etc/pcmcia
etc/perl
etc/php
etc/pki
etc/pm
etc/polkit-1
etc/postfix
etc/ppp
etc/profile.d
etc/proftpd
etc/pulse
etc/python
etc/rc0.d
etc/rc1.d
etc/rc2.d
etc/rc3.d
etc/rc4.d
etc/rc5.d
etc/rc6.d
etc/rcS.d
etc/resolvconf
etc/rsyslog.d
etc/samba
etc/sane.d
etc/security
etc/selinux
etc/sensors.d
etc/sgml
etc/signon-ui
etc/skel
etc/snmp
etc/sound
etc/spamassassin
etc/speech-dispatcher
etc/ssh
etc/ssl
etc/sudoers.d
etc/sysctl.d
etc/sysstat
etc/systemd
etc/terminfo
etc/texmf
etc/thermald
etc/thnuclnt
etc/thunderbird
etc/timidity
etc/tmpfiles.d
etc/ubuntu-advantage
etc/udev
etc/udisks2
etc/ufw
etc/update-manager
etc/update-motd.d
etc/update-notifier
etc/UPower
etc/urlview
etc/usb_modeswitch.d
etc/vim
etc/vmware
etc/vmware-installer
etc/vmware-vix
etc/vulkan
etc/w3m
etc/wireshark
etc/wpa_supplicant
etc/X11
etc/xdg
etc/xml
```

**Comment by lifeforms** [comment]
@gwen001 My apologies, but our switch back to the v4.0/dev branch closed all the v4.1/dev PRs and it turns out it is impossible to reopen or rebase them! Could you send this PR again, but based on the v4.0/dev branch? My apologies!

**Comment by gwen001** [comment]
Done: https://github.com/coreruleset/coreruleset/pull/2560

**Pull request closed without merging**
