### PR TITLE
add some popular http library & scraping framework

### PR DESCRIPTION
**Pull request by Zerorigin**
add some popular http library & scraping framework

### CODE REVIEW

**Comment by azurit** [comment]
Hi and thanks for this cool addition!

Few notes:
 - I would put `ACHE`, `heritrix`, `NutchCVS`, `pyspider` and `crawler4j` into `crawlers-user-agents.data`.
 - Please remove URLs to specific source code file with `User-Agent` header definition, better put them into pull request description.
 - Do you have exact `User-Agent` headers? Would be great to add them into comments togather with URLs.

**Comment by Zerorigin** [comment]
> Few notes:
> 
>     * I would put `ACHE`, `heritrix`, `NutchCVS`, `pyspider` and `crawler4j` into `crawlers-user-agents.data`.
> 
>     * Please remove URLs to specific source code file with `User-Agent` header definition, better put them into pull request description.
> 
>     * Do you have exact `User-Agent` headers? Would be great to add them into comments togather with URLs.


* I couldn't find the description of default User-Agent header in official documentation. 
* So, I put the source code URLs here to make it easier to identify their sources.

* I would put `ACHE`, `heritrix`, `NutchCVS`, `pyspider` and `crawler4j` into `crawlers-user-agents.data`.
* Also, I would remove URLs to specific source code file with `User-Agent` header definition, put them into pull request description.

**Comment by azurit** [comment]
Excellent, can you do these changes in your pull request?

**Comment by Zerorigin** [comment]
> Excellent, can you do these changes in your pull request?

I'm revising it.

**Pull request closed without merging**
