### PR TITLE
Adding 'drop' keyword

### LINKED ISSUE #2211: Drop keyword not blocked for SQL injection
### Description

The following query is not blocked:

https://some.web.site/index.html?q='drop table users;--

But it is blocked if I replace drop with delete, update, etc. This feels inconsistent, so I thought I should report it just in case.

Interestingly, if I add a ";" character after the single quote, then it is blocked:

https://some.web.site/index.html?q='; drop table users;--

### Your Environment

* CRS version:  v3.3.2
* Paranoia level setting: 1
* ModSecurity version: v3.0.5
* Web Server: ingress-nginx on kubernetes v1.21.4 running on Docker Desktop version 4.0.1 with docker engine version v20.10.8

### PR DESCRIPTION
**Pull request by azurit**
- Affected rules: 942200 942350 942360 942362
 - Fixed alphabetical ordering of regexes for rule 942200.

Fixes #2211

### CODE REVIEW

**Comment by dune73** [comment]
Neat PR, thank you, but do you see what's going wrong with the tests?

**Comment by azurit** [comment]
@dune73 No but few last PRs are having the same issues so i assumed it's not my fault. Also, i didn't touch rules which tests are failing. Or am i wrong?

**Comment by dune73** [comment]
I think you are correct. So many PRs are failing. Sorry for the inconvenience.

**Comment by dune73** [comment]
No. Only that it's time to merge.

**Pull request merged**
