### PR TITLE
fix: evasion suffix must be the same everywhere

### PR DESCRIPTION
**Pull request by theseion**

### CODE REVIEW

**Comment by fzipi** [comment]
Looks good. Is this related to an issue, or do we want to add more tests for the additional chars?

**Comment by theseion** [comment]
This is an oversight that I should have fixed a month ago.

**Comment by theseion** [comment]
This PR and #3328 are preparations for the removal of the `*-with-params.ra` files.

**Comment by theseion** [comment]
@fzipi I still need your approval here.

**Review by fzipi — APPROVED** [review]
Looks good. No additional tests for this change, as I said.

**Pull request merged**
