### PR TITLE
feat(91310x): Overhaul 91310x family

### PR DESCRIPTION
**Pull request by dune73**
As discussed in the previous and in the June meeting, it is very hard  to draw
a line between benign, mostly benign and malicious. And because dedicated
attackers will change the user agent anyways.

We have therefore decided to concentrate on a curated list of the most know and most malicious security scanners at PL1 and drop all the rest. Also because dedicated attackers will simply change the UA, so there is little value here anyways.

If you are interested in the discussion around this and at the extensive work that went into the overhauling and expansion of the previous rules, then look into this closed PR https://github.com/coreruleset/coreruleset/pull/3202. It was after intense discussions around this PR that we decided to cut it down.

### CODE REVIEW

**Review by franbuehler — CHANGES_REQUESTED** [review]
Thank you for the PR! Same here: Do we want to delete: scripting-user-agents.data and crawlers-user-agents.data?
Having the goal of the list-update feature in mind: Would it be helpful to add some information to the rules/scanners-user-agents.data file about how the list was created?

**Comment by dune73** [comment]
Removed the 2 files you mentioned and added an intro comment for scanners-user-agents.data.

**Review by franbuehler — APPROVED** [review]
LGTM

**Review by franbuehler — CHANGES_REQUESTED** [review]
Rule 913120 (the removals) sneaked in again. I think you need to pull the v4.0/dev branch before the rebase.

**Comment by dune73** [comment]
You mean in REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf.example? I think I fixed that now.

Note to self: Don't create 3 separate PRs if they all work on the same line of code.

**Review by franbuehler — APPROVED** [review]
LGTM

**Pull request merged**
