### PR TITLE
Rules and tests for detecting UNIX shell history invocation

### PR DESCRIPTION
**Pull request by karelorigin**
This PR contains a fix for a bypass that was originally found and submitted by @hussein98d in `EEXOE9Q1`. Though I've added a few a cases of my own that were not mentioned in `EEXOE9Q1`.

### CODE REVIEW

**Comment by dune73** [comment]
### CRS Bug Bounty PR assessment

* **Rules affected** (list rules): FIXME
* **Paranoia Level addressed** (1, 2, 3, 4, full or explain): FIXME
* **FTW passes** (yes or no) : FIXME
* **Rule(s) picked for solution** (correct or not-correct or explain) : FIXME
* **Risk for false positives** (irrelevant, adequate, substantial or explain) : FIXME
* **Regular expression quality** (inspirational, decent base, needs work, adequate or explain) : FIXME
* **Documentation** (needs work, adequate or explain) : FIXME
* **Tests** (none or some or adequate) : FIXME
&nbsp;
* **Verdict** (Unusable, inspirational, usable, almost perfect or perfect) : FIXME

_This is not meant to be final. As a CRS dev, feel free to comment below and edit this form directly. As committer or observer, feel free to comment below with feedback and we will think about updating the assessment accordingly._

**Comment by RedXanadu** [comment]
@karelorigin New rule 932331 correctly documents "This rule is a stricter sibling of 932330", however the documentation/comments for rule 932330 do not mention that the stricter sibling rule 932331 exists. Could a note/line be added for this, please?

**Comment by karelorigin** [comment]
@RedXanadu done this just now, let me know if that works

**Comment by RedXanadu** [comment]
@karelorigin That's great, thank you!

**Comment by lifeforms** [comment]
Thank you!!

**Pull request merged**
