### PR TITLE
Add (de)compression utilities

### PR DESCRIPTION
**Pull request by RedXanadu**
PR to resolve bug bounty issue from #2710.
Part of **JW2SU88A**.

### CODE REVIEW

**Comment by RedXanadu** [comment]
Looked for all of the compression and decompression utilities I could find on Arch Linux (as of 2022-08-02) and Debian 11.

Added the command paths to `rules/unix-shell.data`.

**Comment by RedXanadu** [comment]
Added (de)compression commands to the pattern file for "Unix direct remote command execution" rule 932150, PL1.

**Comment by RedXanadu** [comment]
Added tests for 932150 and 932160.

**Comment by dune73** [comment]
LGTM. Thank you very much.

**Comment by RedXanadu** [comment]
Merging following approval.

**Pull request merged**
