### PR TITLE
feat(copyright): update copyright to new organization

### PR DESCRIPTION
**Pull request by fzipi**
Signed-off-by: Felipe Zipitria <felipe.zipitria@owasp.org>

We postponed this change for some time, but the copyright needs to be updated.

### CODE REVIEW

**Comment by dune73** [comment]
Thank you.

Would you mind covering the following two files too?
* crs-setup.conf.example
* README.md

**Comment by fzipi** [comment]
Done.

**Comment by dune73** [comment]
Looks good from my perspective. Feel free to merge @lifeforms.

**Comment by fzipi** [comment]
@lifeforms Can you review and merge if all is good?

**Comment by lifeforms** [comment]
Thank you, this is great.

**Pull request merged**
