### PR TITLE
feat(913110): Remove rule (check for security scanner http headers)

### PR DESCRIPTION
**Pull request by dune73**
As discussed in June meeting. This list of HTTP header security scanners are supposed to use. It would be too simple if they would actually use these headers.

Unfortunately, this also removes the x-scanner header which is very useful for CRS fingerprinting. But anyways, it's a useless rule that never triggers and it's time to kick it.

Replaces #3234

### CODE REVIEW

**Review by franbuehler — DISMISSED** [review]
LGTM

**Comment by dune73** [comment]
Removed the 2 conflicts after merge of other PR. Should be ready now. Fingers crossed.

**Comment by franbuehler** [comment]
@dune73 : Another rebase and then this PR can be merged too.

**Review by franbuehler — APPROVED** [review]
LGTM

**Pull request merged**
