### PR TITLE
Unified regexp-assemble toolchain

### PR DESCRIPTION
**Pull request by theseion**
This PR unifies the different scripts into a single toolchain by wrapping all of the decision logic into a single script (`regexp-assemble.py`) and reorganizing the repository.

Conceptually, any assemble data file will now go through the entire pipeline and can opt in to line, block, and file filters (denoted by special comments).

### CODE REVIEW

**Comment by theseion** [comment]
Requires resolution of #2234.

**Comment by fzipi** [comment]
So now it is ready to merge?

**Comment by theseion** [comment]
Not yet :) I want to give it a look over first.

**Comment by theseion** [comment]
I went over it. There's one rule change I had to make (@RedXanadu, that's the one you wrote, 942440) and I'd appreciate a review on that.

Good to merge from my point of view.

**Comment by RedXanadu** [comment]
@theseion Rule 942440 looks fine. I have checked the new version against the existing one, and the regular expression comes out the same in both cases.

The rule comments look inconsistent, though: some of them talk about `./regexp-assemble.pl` and other rules talk about `./regexp-assemble.py`. Is it worth making these consistent?

**Comment by RedXanadu** [comment]
Also, I've re-checked the documentation and it still looks fine, to me. One point: the title is still "How to use regexp-assemble.pl", which probably also needs changing to .py.

**Comment by theseion** [comment]
Thanks @RedXanadu! I've fixed those.

**Comment by RedXanadu** [comment]
@theseion I think some of them lost their leading `/` in that change:

`.regexp-assemble.py 942480`

**Comment by theseion** [comment]
😵‍💫 Thanks!

**Comment by RedXanadu** [comment]
@theseion Does `regexp-compare.py` give clean results across the board at this stage, or are there still a few bumps to be expected?

I can't get it to run without a few regex patterns flagging as changed, at the moment.

**Comment by theseion** [comment]
It doesn't report any mismatches when I run it on this branch... Is your branch clean? Did you make any changes? Can you past the output from one of the failing rules (you can run the script with a rule ID as argument so it doesn't go over everything)?

**Comment by RedXanadu** [comment]
@theseion Are you testing your own branch against itself?

I'm testing v3.4/dev against this branch, to see if the new (computed) regular expressions match the existing ones. Is that not the idea?

**Comment by theseion** [comment]
Oh, I see! Yes, I was testing just my branch. Yes, there are some differences in the expressions. Yes, eventually I would like to have that as part of the test suite for PR's to check new code against the existing rules.

The changed expressions should almost all be equivalent to before, just some reordering or different escapes. But you have a point. I will go over them again and discuss the changes here.

**Comment by theseion** [comment]
# 942440
```
current:      (?:--(?:[\s\r\n\v\f]|[^-]*?-)|[^&-]#.*?[\s\r\n\v\f        (1 / 2)
computed: (?:--(?:[\s\r\n\v\f]|[^-]*?-)|[^&-]#.*?[\s\r\n\v\f        (1 / 2)

current:      ]|[';]--|\/\*!?|\*\/|;?\x00)                              (2 / 2)
computed: ]|;?\x00|[';]--|\/\*!?|\*\/)                              (2 / 2)
```
Equivalent, only reordered branches.

# 934100
```
current:      (?:(?:_(?:\$\$ND_FUNC\$\$_|_js_function)|(?:new\s+        (1 / 4)
computed: (?:_(?:\$\$ND_FUNC\$\$_|_js_function)|(?:new\s+Fun      (1 / 4)

current:      Function|\beval)\s*\(|String\s*\.\s*fromCharCode|f        (2 / 4)
computed: ction|\beval)\s*\(|String\s*\.\s*fromCharCode|func        (2 / 4)

current:      unction\s*\(\s*\)\s*{|this\.constructor)|module\.e        (3 / 4)
computed: tion\s*\(\s*\)\s*{|module\.exports\s*=|this\.const        (3 / 4)

current:      xports\s*=)                                           (4 / 4)
computed: ructor)                                                   (4 / 4)
```
Equivalent. Some reordered branches, removed unnecessary group non-capturing group.

# 932115
 `[too long to put here]`
This is the rule I fixed with @franbuehler. We wrote additional tests for it. The resulting expression is nearly identical but the removal of the two words `sort/` and `sort.*<` results in a couple of grouping changes.

# 920120
```
current:      (?<!&(?:[aAoOuUyY]uml)|&(?:[aAeEiIoOuU]circ)|&(?:[            (1 / 4)
computed: (?:(?<!&[aAoOuUyY]uml|&[aAeEiIoOuU]circ|&[eEiIoOuU        (1 / 4)

current:      eEiIoOuUyY]acute)|&(?:[aAeEiIoOuU]grave)|&(?:[cC]c         (2 / 4)
computed: yY]acute|&[aAeEiIoOuU]grave|&[cC]cedil|&[aAnNoO]ti        (2 / 4)

current:      edil)|&(?:[aAnNoO]tilde)|&(?:amp)|&(?:apos));|['\"        (3 / 4)
computed: lde|&amp|&apos);|['\"=])                                                  (3 / 4)

current:  =]                                                        (4 / 4)
```
Did not exist as a data file before, the expression had been hand crafted, hence the many differences. I've verified this expression manually.

**Comment by RedXanadu** [comment]
I've also re-run those tests (which was made much easier because of your thorough notes above, so thank you!) and I concur with your findings.

Merging now.

**Pull request merged**
