### PR TITLE
932100 932105 add some gtfobins to the blacklist

### PR DESCRIPTION
**Pull request by wfinn**
This adds busybox, eval, expect, pidstat, taskset & watch to rule 932105 to prevent unix command injection bypasses using these gadgets.
For `expect` and `watch` I also match whitespace as I assume these words would lead to many FP otherwise (inspired by who@).
I also added a test for pidstat -e blacklistedcommand.

This is the fix for `NR8OX7W0`.

### CODE REVIEW

**Comment by lifeforms** [comment]
Thank you for re-submitting this PR on the v4.0/dev branch. Sorry for the extra work. I should know better than to mess with Git on a Sunday.

**Comment by gwen001** [comment]
Hi :)

In my PR https://github.com/coreruleset/coreruleset/pull/2563 I added a big list of unix shell, I wonder if it would be worth to also add it here.

Source: https://gtfobins.github.io/#+shell

For instance `flock` is missing and can be used to pass remote commands. It would also help to fix some of my reports.

**Comment by wfinn** [comment]
CRS I'll add gwens suggested gtfobins later today

**Comment by wfinn** [comment]
I've added @gwen001 's suggested gtfobins.
I tried to append @ to everything that I thought would be too common.

**Comment by wfinn** [comment]
Okay I'm done now. Made some other minor changes to the test last moment.

**Comment by dune73** [comment]
### CRS Bug Bounty PR assessment

* **Rules affected** (list rules): FIXME
* **Paranoia Level addressed** (1, 2, 3, 4, full or explain): FIXME
* **FTW passes** (yes or no) : FIXME
* **Rule(s) picked for solution** (correct or not-correct or explain) : FIXME
* **Risk for false positives** (irrelevant, adequate, substantial or explain) : FIXME
* **Regular expression quality** (inspirational, decent base, needs work, adequate or explain) : FIXME
* **Documentation** (needs work, adequate or explain) : FIXME
* **Tests** (none or some or adequate) : FIXME
&nbsp;
* **Verdict** (Unusable, inspirational, usable, almost perfect or perfect) : FIXME

_This is not meant to be final. As a CRS dev, feel free to comment below and edit this form directly. As committer or observer, feel free to comment below with feedback and we will think about updating the assessment accordingly._

**Comment by dune73** [comment]
Thank you very much. This looks like a very good start. Also thank you for the minor fixes on the existing items.

Would you mind to add the `@` to the following commands?

* apt
* capsh (-> false positive _capshot_)
* gem
* pip
* sg
* vi

**Comment by wfinn** [comment]
Should be done, I just added a comment saying "words starting with a-n are in 932100.data" and vice versa.

> Finally, you ran the regex-assembly script yourself successfully. 
> As a new committer could you provide some feedback on the use of said script? Was this a complicated step?

I wasn't sure if I had done it correctly, but it worked easily once I was in `./util`.

I ran this for both rules `python3 regexp-assemble/regexp-assemble.py --log-level DEBUG update 932100` but it's a bit confusing that I could only select one .data file. Maybe I didn't get both changes now?

**Comment by fzipi** [comment]
@wfinn Hey! 👋 Can you rebase and fix conflicts here? Thanks!

**Comment by wfinn** [comment]
Weirdly I can not, the generation breaks for me.

I did this:
- fetch new dev branch
- rebase onto dev branch
- merge (mostly just accept both changes, in .conf your state)
- try to regenerate to integrate my changes into the .conf again <- this doesn't work

**CURRENT STATE IS BROKEN / INCOMPLETE**

Currently I get "lib.operators.assembler.NestingError: Nesting error on line 285, nesting level 2" when I run "update 932100", I used to get another error before. I dont get it, line 285 would be the "words startign with m" comment...

I can't get it to work rn, might be able to look at it again, but I'd like your help here. I think the merge is done correctly, but seemingly not. Can someone take a look?

**Comment by fzipi** [comment]
Try updating also git submodules.

**Comment by wfinn** [comment]
Was a stupid merge error... I deleted `##<` 😅

**Comment by lifeforms** [comment]
Thank you! 🥳

**Pull request merged**
