### PR TITLE
Adding word boundary to lower FPs

### LINKED ISSUE #2075: Rule: 942190: False positive 0202
### Description

 [-:error] ModSecurity: Warning. Pattern match "(?i:(?:[\\"'`](?:;?\\\\s*?(?:having|select|union)\\\\b\\\\s*?[^\\\\s]|\\\\s*?!\\\\s*?[\\"'`\\\\w])|(?:c(?:onnection_id|urrent_user)|database)\\\\s*?\\\\([^\\\\)]*?|u(?:nion(?:[\\\\w(\\\\s]*?select| select @)|ser\\\\s*?\\\\([^\\\\)]*?)|s(?:chema\\\\s*?\\\\([^\\\\)]*?|elect.*?\\\\w?user\\\\()|in ..." at ARGS:q. [file "../../../coreruleset-3.4-dev/rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf"] [line "200"] [id "942190"] [msg "Detects MSSQL code execution and information gathering attempts"] [data "Matched Data: User( found within ARGS:q: appUser(sitename,user)"] [severity "CRITICAL"] ["OWASP_CRS/3.3.0"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-sqli"] [tag "paranoia-level/1"] [tag "OWASP_CRS"] [tag "capec/1000/152/248/66"] [tag "PCI/6.5.2"] [hostname "*******************"]

### Audit Logs / Triggered Rule Numbers

* CRS version (e.g., v3.2.0):
* Paranoia level setting: 1
* ModSecurity version (e.g., 2.9.3):
* Web Server and version (e.g., httpd 2.4.41):
* Operating System and version: RHEL 7.9

### Confirmation

[ ] I have removed any personal data (email addresses, IP addresses,
    passwords, domain names) from any logs posted.

Hi Guys,

I am getting this false positive when I click a particular tab in my website. Could you please help me that this rule can be removed or we have any other fix?

### PR DESCRIPTION
**Pull request by azurit**
This fixes #2075.

### CODE REVIEW

**Comment by lifeforms** [comment]
@azurit I think you have forgotten to put also the compiled new version also in REQUEST-942-APPLICATION-ATTACK-SQLI.conf 🙈

**Comment by lifeforms** [comment]
Also in my opinion ideally a `\b` could be added in front of the other keywords (select, union etc) as well.

**Comment by azurit** [comment]
> @azurit I think you have forgotten to put also the [compiled new version](https://coreruleset.org/20190826/optimizing-regular-expressions/) in REQUEST-942-APPLICATION-ATTACK-SQLI.conf see_no_evil

I didn't forget, I just thought this is going to compile while doing a new release. Will fix it, thank you.

**Comment by azurit** [comment]
@lifeforms These tests won't pass:

```
data: "FROM+INFORMATION_SCHEMA.%0A"
data: "%27%3BSELECT+P%0A"
data: "UnIon+seleCt%0A"
```
I'm not MSSQL expert so i'm not sure if using + instead of a space is correct syntax. Also, we missed %3B i.e. semicolon (;) for at least SELECT command (i will add it).

**Comment by dune73** [comment]
We have a ton of test failures after the changes of @azurit here. Anybody see why this is the case? I'm a bit at a loss here.

**Comment by theseion** [comment]
@azurit You forgot to add the `(?i:...)` flag (explicitly stated in the rule comment). I can't push to this branch, so you'll have to fix it yourself. With that change, the tests are green on my end.

**Comment by azurit** [comment]
@theseion Thanks!

Ready to be merged.

**Comment by franbuehler** [comment]
Meeting decision June (https://github.com/coreruleset/coreruleset/issues/2074#issuecomment-856173925):
@theseion will review this PR.

**Comment by theseion** [comment]
>I'm not MSSQL expert so i'm not sure if using + instead of a space is correct syntax. Also, we missed %3B i.e. semicolon (;) for at least SELECT command (i will add it).

@azurit are you planning to make these changes? I don't see how they are relevant to the PR.

**Review by theseion — CHANGES_REQUESTED** [review]
Looks good to me. One thing I'd like to see is an additional tests for the reported FP. That will guard against regression.

**Comment by azurit** [comment]
> > I'm not MSSQL expert so i'm not sure if using + instead of a space is correct syntax. Also, we missed %3B i.e. semicolon (;) for at least SELECT command (i will add it).
> 
> @azurit are you planning to make these changes? I don't see how they are relevant to the PR.

No.

**Comment by azurit** [comment]
@theseion Done.

**Review by theseion — APPROVED** [review]
Perfect!

**Comment by dune73** [comment]
There is a conflict that awaits resolution. Other than that, we're done, are not we?

**Comment by azurit** [comment]
There were no conflicts when i was doing my last commit. What happened?

**Comment by dune73** [comment]
942190 was updated in the meantime: https://github.com/coreruleset/coreruleset/commit/a37e0308571df500b538a9d122f5bd9ae3b4f129

Sorry for the inconvenience, but this happens from time to time.

Can you resolve it?

**Comment by azurit** [comment]
I don't understand how am i supposed to resolve it - it's already resolved from my point of view.

**Comment by dune73** [comment]
I see your point, but then I think you need to rebase on the v3.4/dev _after_ the said merge.

**Comment by franbuehler** [comment]
Meeting decision July: https://github.com/coreruleset/coreruleset/issues/2141#issuecomment-874288876
@theseion and @azurit will make this PR ready to be merged. Unfortunately some tests are failing.

**Comment by theseion** [comment]
@azurit All you need to do is to regenerate the regular expression (the change from the previous PR got lost when you merged, that's why the two tests for that PR fail).

**Comment by azurit** [comment]
@theseion Thanks! Should be ok now.

**Comment by dune73** [comment]
Apparently merging this is long overdue. Merging now.

Thank you for the PR @azurit and the reviews / support @theseion and @franbuehler.

**Pull request merged**
