### PR TITLE
re2: use compatible syntax in rule 953120

### LINKED ISSUE #2354: Rethink/rewrite rule 953120 for re2 support
### Proposed solution

The rule matches on the response body `<\?(?!xml)`, looking to detect the presence of the PHP open tag "`<?`" or "`<?php`" in output.

### Alternatives

Looking at [PHP tags](https://www.php.net/manual/en/language.basic-syntax.phptags.php) they can use `<\?\s+`, `<\?\=\s+` or `<\?php\s+` for the starting tag.

I think we should change it to match exactly for that, like: `<\?(?:\=|php)?\s+`.

### PR DESCRIPTION
**Pull request by fzipi**
Signed-off-by: Felipe Zipitria <felipe.zipitria@owasp.org>

Remove pcre2 only syntax.

Fixes #2354

### CODE REVIEW

**Comment by fzipi** [comment]
Got a working test after we merge #2359 .

**Comment by fgsch** [comment]
We might want to put this live somewhere to check for FPs but looks good to me.

**Comment by fzipi** [comment]
Definitely. Maybe @theMiddleBlue can take a look at these also, or make it live somewhere.

**Comment by theMiddleBlue** [comment]
Hey! If you want I can bring up an apache backend on the sandbox based on this PR :) so we can test it directly on our sandbox

**Comment by fzipi** [comment]
This can only be tested after we merge #2359 .

**Comment by fzipi** [comment]
Added tests, now this can be merged.

**Comment by fzipi** [comment]
@lifeforms Any comment here, or just merge?

**Comment by fzipi** [comment]
Merging then.

**Pull request merged**
