### PR TITLE
920470: Allow # character

### PR DESCRIPTION
**Pull request by azurit**
Adding test for pull request #1839.

### CODE REVIEW

**Comment by azurit** [comment]
Well, there was a blank line at the end of the file so i preserved it..

**Comment by dune73** [comment]
Thank you very much. Most welcome.

@azurit : would you mind sending me your email address? DM welcome. (And sorry if I am supposed to have it. Can't find it in my files.)

**Comment by azurit** [comment]
@dune73 i sent you an e-mail to your github email address

**Comment by azurit** [comment]
Am i supposed to do something with these failed tests? Why is it suddenly failing if it wasn't before?

**Comment by airween** [comment]
hi @azurit,

> Am i supposed to do something with these failed tests? Why is it suddenly failing if it wasn't before?

if I'm right, the `@rx` operator tries to match [this](https://regex101.com/r/XE9Xua/1) pattern with the subject - which is **not** matched.

As the operator in rule [has a negation](https://github.com/coreruleset/coreruleset/blob/v3.4/dev/rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf#L915) (`!@rx`), therefore the rule will triggered.

**Comment by azurit** [comment]
I wasn't writing that part of the rule. Sorry, i don't understand what am i supposed to do here.

**Comment by airween** [comment]
> I wasn't writing that part of the rule. Sorry, i don't understand what am i supposed to do here.

yes, the rule as is, you don't need to touch it :).

What's your idea in the test case what you added?

If you change the `no_log_contains` by `log_contains`, then the test will pass.

This means the given CT header doesn't match with the regex, so the rule is triggered.

**Comment by lifeforms** [comment]
The misunderstanding probably was, this test is testing a new rule change, made by @azurit in #1839. The rule should *not* fire on this input.

I could not merge or edit PR #1839, so I have applied the rule change (written by @azurit) to #1856.

All tests are green, so we can merge both the change and the test!

Thanks again @azurit !

**Pull request merged**
