### PR TITLE
Backslashes 932190

### PR DESCRIPTION
**Pull request by theseion**
I have a couple of questions that I hope @theMiddleBlue can answer. Until then, this PR will remain in draft state.

### CODE REVIEW

**Comment by theMiddleBlue** [comment]
all changes seem legit to me, thank you!
I think that the first test case should check for something like `cat+/et*/*wd` and not SQL syntax

**Comment by theseion** [comment]
Yeah, that's better.

Based on your blog posts I also added tests for mixed evasion with single quote and backslash and case insensitive file systems. All three evasions are handled by `t:cmdLine`.

**Review by RedXanadu — APPROVED** [review]
Looks good from a backslash perspective, as the backslashes have been eliminated from the regular expression :grin:

**Review by fzipi — APPROVED** [review]
LGTM also!

**Comment by theseion** [comment]
Ok. I'll merge this. @theMiddleBlue yell at me if you're not happy :)

**Pull request merged**
