### PR TITLE
Little performance fixies

### PR DESCRIPTION
**Pull request by azurit**
According to documentation, `@pmFromFile` / `@pm` is doing case-**in**sensitive match so `t:lowercase` is not needed.

### CODE REVIEW

**Comment by dune73** [comment]
Very nice. Thank you @azurit. Did you check every occurrence or do we need to do this systematically?

**Comment by azurit** [comment]
Yes i did!

**Comment by lifeforms** [comment]
TODO: test out on responses and merge.

Also goes into the incubator.

**Comment by azurit** [comment]
@lifeforms Not this one! This: https://github.com/coreruleset/coreruleset/pull/2116

**Comment by lifeforms** [comment]
@azurit Haha oops!

**Pull request merged**
