### PR TITLE
fix(933160): php func call evasion fix

### PR DESCRIPTION
**Pull request by s0md3v**
Issue: `T8GVTLJO`

Description: `"` can be used a separator (e.g. `"system"()`) to evade detection in php.

Fix: Blacklist `"` as a seperator in php function calls.

### CODE REVIEW

**Comment by dune73** [comment]
### CRS Bug Bounty PR assessment

* **Rules affected** (list rules): FIXME
* **Paranoia Level addressed** (1, 2, 3, 4, full or explain): FIXME
* **FTW passes** (yes or no) : FIXME
* **Rule(s) picked for solution** (correct or not-correct or explain) : FIXME
* **Risk for false positives** (irrelevant, adequate, substantial or explain) : FIXME
* **Regular expression quality** (inspirational, decent base, needs work, adequate or explain) : FIXME
* **Documentation** (needs work, adequate or explain) : FIXME
* **Tests** (none or some or adequate) : FIXME
&nbsp;
* **Verdict** (Unusable, inspirational, usable, almost perfect or perfect) : FIXME

_This is not meant to be final. As a CRS dev, feel free to comment below and edit this form directly. As committer or observer, feel free to comment below with feedback and we will think about updating the assessment accordingly._

**Comment by RedXanadu** [comment]
@s0md3v Your test's description is making the linter unhappy. Maybe you could try putting it inside single quotes or something similar?

**Comment by fzipi** [comment]
@s0md3v Looks like permissions on the three files have been changed to 0755. Was that on purpose? Can you revert that permission change?

**Comment by lifeforms** [comment]
I think the `desc: "func"(` is tripping the YAML verification. Could you try to fix that?

**Comment by lifeforms** [comment]
Would this also work if a hacker sends concatenated strings like `"sys"."tem"(ls)` ?

**Comment by lifeforms** [comment]
Could this also work against a bypass with string concatenation e.g. `("sys"."tem")(ls);` ?

**Comment by lifeforms** [comment]
There's a linter error:

```
 test_title: 933160-40
     desc: "func"(
 Check failure on line 633 in tests/regression/tests/REQUEST-933-APPLICATION-ATTACK-PHP/933160.yaml
 GitHub Actions/ check-syntax

tests/regression/tests/REQUEST-933-APPLICATION-ATTACK-PHP/933160.yaml#L633
syntax error: expected <block end>, but found '<scalar>' (syntax)
```

It is probably due to `"func"(` , could this be updated @s0md3v ?

**Comment by dune73** [comment]
Assigned @theMiddleBlue based on the separate spreadsheet in our drive.

**Comment by theMiddleBlue** [comment]
Thanks @fzipi 

are you saying that the new regex has not been generated with the regex assemble tool? I've the following error while running the command you used:

```shell
$ ./regexp-assemble.py compare 933160
Processing 933160, chain offset 0
Traceback (most recent call last):
  File "/home/themiddle/git/s0md3v-coreruleset/util/regexp-assemble/./regexp-assemble.py", line 227, in <module>
    namespace.func(namespace)
  File "/home/themiddle/git/s0md3v-coreruleset/util/regexp-assemble/./regexp-assemble.py", line 154, in handle_compare
    comparer.run(False)
  File "/home/themiddle/git/s0md3v-coreruleset/util/regexp-assemble/lib/operators/comparer.py", line 9, in run
    self.perform_compare_or_update(process_all, self.compare_regex)
  File "/home/themiddle/git/s0md3v-coreruleset/util/regexp-assemble/lib/operators/parser.py", line 33, in perform_compare_or_update
    self.process_regex(
  File "/home/themiddle/git/s0md3v-coreruleset/util/regexp-assemble/lib/operators/parser.py", line 59, in process_regex
    parser.parser.parse(handle.read())
  File "/usr/local/lib/python3.10/dist-packages/ply/yacc.py", line 333, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/usr/local/lib/python3.10/dist-packages/ply/yacc.py", line 1063, in parseopt_notrack
    lookahead = get_token()     # Get the next token
  File "/usr/local/lib/python3.10/dist-packages/ply/lex.py", line 386, in token
    newtok = self.lexerrorf(tok)
  File "/usr/local/lib/python3.10/dist-packages/msc_pyparser.py", line 385, in t_ANY_error
    raise Exception(output, {'cause': "lexer", 'line': li+1, 'position': t.lexer.lexpos, 'column': pos})
Exception: ('Lexer error: illegal token found in line 1 at pos 0, column 0\n__autoload\n^', {'cause': 'lexer', 'line': 1, 'position': 0, 'column': 0})
```

any help?

**Comment by theMiddleBlue** [comment]
tested this PR on my local sandbox. ready to merge for me (if for you it's ok)

**Comment by theMiddleBlue** [comment]
> Weird that we are changing the file util/regexp-assemble/data/932110.data here. I understand the perm change, but maybe that should be in a new PR?

I can checkout the file and fix the perm in a separate PR if needed

**Review by fzipi — APPROVED** [review]

**Pull request merged**
