### PR TITLE
fix 942350

### PR DESCRIPTION
**Pull request by theMiddleBlue**

### CODE REVIEW

**Comment by theMiddleBlue** [comment]
regex built also with:

```shell
python3 regexp-assemble.py 942350
(?i)(?:;\s*?(?:(?:(?:trunc|cre|upd)at|renam)e|d(?:e(?:lete|sc)|rop)|(?:inser|selec)t|alter|load)\b\s*?[\[(]?\w{2,}|create\s+function\s?.+\s?returns)
```

**Comment by theMiddleBlue** [comment]
before fix:
```shell
0,00s user 0,01s system 0% cpu 4,524 total
```

with the regex in this PR:
```shell
0,00s user 0,00s system 0% cpu 1,204 total
```

IMO ready to merge, any objections?

**Comment by dune73** [comment]
I'm a bit out of the loop here. Would you mind briefly explaining what your regex change fixes outside of the performance impact. It's a different pattern, now, is not it? We don't lose detection ability this way?

**Comment by dune73** [comment]
Returning to this, I just don't see the point of this regex: `... function\s?.+\s? ...`

This is effectively the same as `... function.+ ...` is not it? And is not that an invitation to FPs?

Can't we do `... function\b.+\b ...` instead?

**Comment by franbuehler** [comment]
[Meeting decision December](https://github.com/coreruleset/coreruleset/issues/2291#issuecomment-987122691): @theseion will take a look at this PR.

**Comment by theseion** [comment]
> This is effectively the same as `... function.+ ...` is not it? And is not that an invitation to FPs?

Yes

> Can't we do `... function\b.+\b ...` instead?

Yes but we need to be careful. `\b.+\b` is not the same as `\b?.+\b?`. Without the qualifier the word boundaries are now mandatory. Before, something like this would be valid: `create functionALERTreturns`. We need to know exactly  what that expression should match (or better, how lenient the parsers of Postgres and MySQL are in that case).

**Comment by theMiddleBlue** [comment]
this PR aims to solve a ReDoS problem, it is not a regex refactor or improvement. It doesn't change much in terms of detection. Since it's a performance problem (critical I would say) can we merge it and then think about improvements?

**Comment by theseion** [comment]
I don't quite understand the change then. The original regex requires at least one whitespace character while your change allows for no whitespace character. Shouldn't the change be `create\s+function\s.+\sreturns`?

**Comment by theMiddleBlue** [comment]
it's just a minimal change to keep all payload matching and fix the redos. no problem for me to change it to `\s.+\s`

**Comment by theMiddleBlue** [comment]
if for you it's ok, I would like to merge it

**Pull request merged**
