### PR TITLE
Fix FP in rule 942190 with keyword UNION

### PR DESCRIPTION
**Pull request by franbuehler**
This PR fixes issue #2047 (False Positive with "Union von" rule id 942190) by extending the keyword `union`.
`Union` alone does not make sense. But it makes sense when a `distinct`, `all` or `select` follows the `union`.

We already fixed a similar FP in rule 942360 in 2018 in this [commit here](https://github.com/coreruleset/coreruleset/commit/6c5f4550f874f66b4b3d9d0222336cfbf4b26a23#diff-ca2e05f6521d61919bf1d74d07d511cd1ccef6bdf553103cac21c0d757979044R132).

I also fixed some tests. They did no longer match, because I extended the regular expression in the rule. 
And I added a new test, that tests if the reported FP is gone.

### CODE REVIEW

**Comment by dune73** [comment]
Thank you for this fix @franbuehler.

The regex used to have a `\b` after `Union` and the other keywords still do. But your new regex no longer does. I get the feeling it is not necessary to do `\b` before `\s`. Maybe we should clean it up. If it is necessary, then you ought to add it too.

**Comment by franbuehler** [comment]
Hi @dune73 

Thank you for spotting this detail!

The new regex still has the \b, but I added the new keywords in between, for example I added the `all` between `union` and `\b\s*?[^\s]`:
`[\"'`];?\s*?union\s*?all\b\s*?[^\s]`.

Because the \s is optional (*), I think it's good to have the word boundary.

Current regex: `\s*?union\s*?all\b\s*?[^\s]`
matches: union all select

Without word boundary: `\s*?union\s*?all\s*?[^\s]`
matches: union allselect

With this important detail in mind, I think it's better to extend my proposed regex to (to add an additional word boundary):
`[\"'`];?\s*?union\b\s*?all\b\s*?[^\s]`.

So that `union all select` matches, but `unionall select` does not.

What do you think? I'll change my PR...

**Comment by dune73** [comment]
Agreed. That's better. Thank you very much.

**Comment by dune73** [comment]
Thank you for your fix, @franbuehler. Merging now.

**Pull request merged**
