### PR TITLE
fix: issue dependencies only work from PRs

### PR DESCRIPTION
**Pull request by theseion**
The action we are using only works on PRs. It can handle issues as dependencies but the container has to be a PR.

### CODE REVIEW

**Review by fzipi — APPROVED** [review]
Ok, so we remove.

**Comment by fzipi** [comment]
@theseion You are removing everything, right?

**Comment by theseion** [comment]
Ups! No, I forgot to add the new files 😅

**Review by fzipi — APPROVED** [review]
LGTM now.

**Pull request merged**
