### PR TITLE
WordPress Site Health Exclusion Rule

### PR DESCRIPTION
**Pull request by robertdeboer**
Add a WordPress Exclusion Rule

WordPress has a site health page in the admin portal that triggers 2 data leakages errors in the current default rule set up even when using the WordPress exclusion package.
* 951220 - 951-DATA-LEAKAGES-SQL.conf 
* 953110 - 951-DATA-LEAKAGES-PHP.conf

This adds an exclusion rule for the site health page to disable these 2 rules.

This implements #1919

### CODE REVIEW

**Comment by robertdeboer** [comment]
@airween This is the PR you requested.

**Comment by dune73** [comment]
Thank you for your contribution @robertdeboer.

The tests are failing since you have a rule ID collision in your PR. Would you mind using the rule ID `9002840` instead of `9002910`?

**Comment by robertdeboer** [comment]
@dune73 I have updated the rule ID as requested.

**Comment by dune73** [comment]
Thank you very much.

**Comment by airween** [comment]
LGTM - thanks @robertdeboer!

**Comment by dune73** [comment]
Time to merge this then, @robertdeboer. Thank you for your contribution.

**Pull request merged**
