### PR TITLE
Whitelist for YAM package manager

### PR DESCRIPTION
**Pull request by azurit**
Fix for issue #1969 by doing simple whitelist, as discussed on Monthly Chat Agendas of January.

### CODE REVIEW

**Comment by lifeforms** [comment]
@azurit Slated for merge. We only need some tests.

Could you find some real YUM User-Agent strings to add one or more negative tests?

And also a positive test for the real Grabber that we want to block. From https://tools.kali.org/web-applications/grabber I downloaded the code and found the UA for Grabber. It's: `Grabber/0.1 (X11; U; Linux i686; en-US; rv:1.7)’`

After test, I will review and merge.

**Comment by lifeforms** [comment]
Another UA to whitelist would be `mozilla/5.0 ecairn-grabber/1.0 (+http://ecairn.com/grabber)` which is seen by a user commonly and does not seem to be a vulnerability scanner. Would recommend adding this one too.

**Comment by azurit** [comment]
Do we really want to whitelist ecairn-grabber? Isn't it some kind of SEO service which is grabbing sites with really hardcore speed (no matter if they goes down) and then selling mined data?

**Comment by dune73** [comment]
You could argue that ecairn ought to be whitelisted in 913100, yet it should be flagged by 913102.

**Comment by azurit** [comment]
So, should i whitelist it in 913100 but add into 913102?

**Comment by dune73** [comment]
Actually, I think yes. But maybe @lifeforms wants to chime in too.

**Comment by lifeforms** [comment]
I agree, let's whitelist it here, but put ecairn in 913102.

**Comment by dune73** [comment]
Thank you @azurit. Will you do a separate PR for 913102?

Other than that, ready to be merged from my point of view.

**Comment by dune73** [comment]
Ah, there we go #2024. :)

**Comment by azurit** [comment]
It's already there: https://github.com/coreruleset/coreruleset/pull/2024

**Pull request merged**
