### PR TITLE
fix: Fix fps 932260

### LINKED ISSUE #3288: Rule 932260 false positive with "scheduledAt" keyword
### Description

Our web application needs to sort events, we have different sorts and one of them is against a scheduledAt field.

### How to reproduce the misbehavior

```
curl https://sandbox.coreruleset.org/events?sortBy=scheduledAt
```

### Your Environment

* CRS version (e.g., v3.3.4): default from sandbox
* Paranoia level setting (e.g. PL1) : PL1
* ModSecurity version (e.g., 2.9.6): default from sandbox
* Web Server and version or cloud provider / CDN (e.g., Apache httpd 2.4.54): default from sandbox
* Operating System and version: default from sandbox

### Confirmation

[X] I have removed any personal data (email addresses, IP addresses,
    passwords, domain names) from any logs posted.

Blocked by #3276

### PR DESCRIPTION
**Pull request by RedXanadu**
PR adds new false positive tests to catch 'sched' and 'eval' (e.g. FPs with plain English words "schedule" and "evaluation").
'sched' and 'eval' added to exclusion list "unix-shell-fps-pl1.ra".
Regular expression for rule 932260 regenerated.
Fixes #3288

### CODE REVIEW

**Comment by RedXanadu** [comment]
Ahhh, hang on:

Is the true meaning of this line:
`##! To automatically add exclusions for English words from the sources, run the following:`

actually more like:
```
##! This list is an automatically generated list of exclusions of English words
##! from the above-listed sources. To regenerate this list, run the following:
```

If that is the case, then no. And I don't currently have easy access to WordNet. Help!

**Comment by theseion** [comment]
Yes, precisely. I ran the update script, just to be sure and yes, existing entries will not be removed, so your change works.

**Review by theseion — APPROVED** [review]

**Comment by RedXanadu** [comment]
Ah, okay.

But doesn't this
```
##! ed -s regex-assembly/exclude/unix-shell-fps-pl1.ra <<EOF
##! $((body_start - 1)),\$d
```
clear out the old file? How would a manual entry stay in place?

**Comment by theseion** [comment]
Yes, but the original entries in the list are first read with 

```shell
##! original="$(grep -vE '^[#$]' regex-assembly/exclude/unix-shell-fps-pl1.ra)"
```

**Review by dune73 — APPROVED** [review]

**Comment by dune73** [comment]
Looks good to me. Thanks for sorting this out.

Merging now.

**Pull request merged**
