### PR TITLE
Block zerodium PHP backdoor: restricted header user-agentt

### PR DESCRIPTION
**Pull request by theMiddleBlue**
as reported here https://www.bleepingcomputer.com/news/security/phps-git-server-hacked-to-add-backdoors-to-php-source-code/

### CODE REVIEW

**Comment by dune73** [comment]
I am rather weary to merge this rule. I think our audience does not need this rule.

Let's discuss this in the chat.

**Comment by theMiddleBlue** [comment]
tnx @dune73, maybe I misinterpreted what we wrote on slack about this backdoor, sorry! sure let's talk about this in the next meeting. I convert this PR as a draft

**Comment by dune73** [comment]
Thanks.

I think we are not 100% sure this backdoor has really being installed anywhere. Let's assume it is installed by oblivious users who managed to install a nightly build / master branch checkout and then managed to ignore the news there was a hole.

And then you have a group of users that install bleeding edge CRS from master.

I think the two groups do not overlap. So including this rule won't protect those affected, but it means an additional and futile rule for everybody else.

Easy alternative that only occurred to me now: We could add User-Agentt to the list of restricted / forbidden headers - assuming nobody uses User-Agentt for benign purposes.

**Comment by theMiddleBlue** [comment]
seems legit, and I agree with you. I try to replace this with a new entry on the restricted request header rules (900250, 901165)

**Comment by dune73** [comment]
Thank you. And thank you for insisting with proposing a PR. I would have ignored this myself, but together we have now found a light solution, that does not hurt.

**Comment by dune73** [comment]
Let's cover this briefly during the chat on Monday. Otherwise, it's ready to be merged, I think.

**Pull request merged**
