### PR TITLE
fix: change order of base64decode in NODEJS Attack

### PR DESCRIPTION
**Pull request by IppSec**
Fix issue in: https://github.com/coreruleset/coreruleset/issues/3182

### CODE REVIEW

**Review by theseion — CHANGES_REQUESTED** [review]
Thanks @IppSec! Please add a test case for this issue.

**Comment by IppSec** [comment]
> Thanks @IppSec! Please add a test case for this issue.

I am not sure how.  Is there any instructions?  The linked issue has details about the slight change.

**Comment by RedXanadu** [comment]
Hi @IppSec,

We have guidelines / templates / examples for tests available here:
https://coreruleset.org/docs/development/contribution_guidelines/#writing-tests

You'll want to look at this file (and you can use the existing tests there for help / as a template, too):
https://github.com/coreruleset/coreruleset/blob/v4.0/dev/tests/regression/tests/REQUEST-934-APPLICATION-ATTACK-GENERIC/934100.yaml

**Comment by dune73** [comment]
@IppSec Are you still interested to finish this PR or should we take over?

**Comment by RedXanadu** [comment]
We need to overhaul all of the rules in REQUEST-934-APPLICATION-ATTACK-GENERIC.conf that use the base64Decode transformation. This is one of those rules, but I think the approach needed is slightly different (a double decode is needed, I think, based on the previous evasion technique that was discussed.) I could take a look at this, hopefully sometime soon.

(More information: https://github.com/coreruleset/coreruleset/issues/3182#issuecomment-1497615073, https://github.com/coreruleset/coreruleset/pull/3203)

**Comment by dune73** [comment]
Let's discuss this tonight.

**Comment by RedXanadu** [comment]
After double-checking, I can confirm that this was superseded by the work (fix) that was merged in #3203.

Closing this particular PR.

**Pull request closed without merging**
