### PR TITLE
Remove negative look behind: clean repository

### PR DESCRIPTION
**Pull request by theseion**
Removed negative look-behind processing
    
Removed mention from data files
    
Removed look-behind conversion script
    
Removed processor from regexp-assemble.py
    
Updated readme

Relates to https://github.com/coreruleset/coreruleset/pull/2360

This is PR 4 of 4 that replace https://github.com/coreruleset/coreruleset/pull/2360.

### CODE REVIEW

**Comment by theseion** [comment]
This is the last PR in the series @fzipi @fgsch. Please take a look.

**Comment by fzipi** [comment]
@theseion You need to rebase this one also.

**Comment by theseion** [comment]
You're right, thanks.

**Review by fzipi — APPROVED** [review]
LGTM. 🧹

**Pull request merged**
