### PR TITLE
Refactor 920400 test with a positive and a negative test cases

### PR DESCRIPTION
**Pull request by M4tteoP**
Hi there, just a little idea following https://github.com/coreruleset/coreruleset/issues/2876.

This PR proposes to:
- remove the current `920400-1` test (it is looking for `expect_error: true` and not really triggering the rule `920400`).
- replace it with a positive and a negative test cases, heavily inspired by https://github.com/coreruleset/coreruleset/pull/2285.

### CODE REVIEW

**Comment by airween** [comment]
@M4tteoP, just a side note: we have a [script](https://github.com/coreruleset/coreruleset/tree/v4.0/dev/util/find-max-datalen-in-tests) until the `tools` directory, which finds the longest body length among the tests. Do you think we should add the feature that find this value too?

**Comment by franbuehler** [comment]
Thank you for this PR! It seems that we now have a valid testcase for your environment and in addition it seems to be working for our regression tests too.

**Comment by M4tteoP** [comment]
Hi @airween, thanks, I ran the script to define `MAX_FILE_SIZE: "64100"` selecting a number between the maximum one used, but less than the one you selected for `COMBINED_FILE_SIZES`. Still, maybe I'm not fully grasping why we have to be particularly careful about this value. Being set only for testing, and running the engine in DetectionOnly, even if the rule could be accidentally triggered running other tests, both ids will be in the log, not impacting other tests. Or maybe, we are aiming to trigger exclusively the specific rule with each test (this is what I tried to achieve with `64100`). Are we?
That being said, I see value to put it high enough in order to not create too much noise inside the logs

**Comment by fzipi** [comment]
I can't wait to be able to use go-ftw to test using just `data: 'foo={{ "1" | repeat 62000 }}'`.

On the comment about triggering other rules, we are trying always to be extra careful on which rules we are triggering so we get better output when running in cloud mode.

**Comment by M4tteoP** [comment]
I see! Thanks @fzipi! So, if the following logic sounds good:
> selecting a number between the maximum one used and the one you selected for COMBINED_FILE_SIZES

Could it be okay just add some context also about MAX_FILE_SIZE inside the same [find-max-datalen-in-tests readme](https://github.com/coreruleset/coreruleset/tree/v4.0/dev/util/find-max-datalen-in-tests)?

**Comment by franbuehler** [comment]
We can add a comment about `MAX_FILE_SIZE` in [find-max-datalen-in-tests readme](https://github.com/coreruleset/coreruleset/tree/v4.0/dev/util/find-max-datalen-in-tests).

But I think this PR here is ready to be merged. I'll approve it.

**Review by franbuehler — APPROVED** [review]

**Comment by franbuehler** [comment]
@airween: like we discussed right now, could you please extend the script to also check for `MAX_FILE_SIZE`?

**Comment by dune73** [comment]
Thank you @M4tteoP. Merging now.

**Pull request merged**
