### PR TITLE
fix: range expressions must not start with `\v`

### LINKED ISSUE #3610: Rule syntax error
Syntax error on these rules:
- REQUEST-920-PROTOCOL-ENFORCEMENT.conf
- REQUEST-922-MULTIPART-ATTACK.conf
- REQUEST-934-APPLICATION-ATTACK-GENERIC.conf

### PR DESCRIPTION
**Pull request by theseion**
Fixes #3610

### CODE REVIEW

**Comment by theseion** [comment]
The lint failure is expected. We first need to merge https://github.com/coreruleset/crs-toolchain/pull/137.

**Comment by theseion** [comment]
@superlgn, @airween Could you test the fixed expressions in this PR? `\v` has now been replaced with `\0xb` in character classes.

**Comment by airween** [comment]
> @superlgn, @airween Could you test the fixed expressions in this PR? `\v` has now been replaced with `\0xb` in character classes.

I pulled your repo and tried it with my Apache2, everything looks fine. I can take a look in detail tomorrow (test few regexes with my tool).

**Comment by airween** [comment]
I run a test with my [tool](https://gist.github.com/airween/5c08626531c97dc63c2f57d9e4bf068e) against all regexes, and looks everything is fine.

Please fix the [lint](https://github.com/coreruleset/coreruleset/actions/runs/8317990853/job/22759407174?pr=3615#step:12:159) error, and I can merge it.

**Comment by theseion** [comment]
Thanks @airween ❤️!

**Review by dune73 — APPROVED** [review]

**Comment by dune73** [comment]
Don't forget to add a remark in CONTRIBUTING.md or somewhere.

**Comment by theseion** [comment]
> Don't forget to add a remark in CONTRIBUTING.md or somewhere.

About what? We simply modified the automation, nothing to be done by devs manually.

**Comment by dune73** [comment]
Ah, sorry. I thought you had changed the source regexes. But true, the change would include the ra files then. Did not connect the dots.

**Pull request merged**
