### PR TITLE
Updated comment on 920520 to explain the value of the header length check

### PR DESCRIPTION
**Pull request by theseion**
Removed obsolete comment from regex data file

This addresses the question from #2357.

### CODE REVIEW

**Comment by theseion** [comment]
A formula would be nice, so that future improvements to the rule could be based on that formula. But if there's no formula, I think it's good enough.

**Comment by fzipi** [comment]
I think the content of this image was part of the input we used.
image

**Review by franbuehler — APPROVED** [review]
LGTM

**Comment by theseion** [comment]
So those are your own measurements? I wasn't able to find any third party resource that offered any such statistics for the `Accept-Encoding` header.

**Comment by fzipi** [comment]
Those were made in the crs sandbox. We can ask the `#coreruleset` channel in slack to see if other people can chime and bring us the top 5 longest headers on their servers. I reckon it might be difficult if they don't have those logs.

**Review by fzipi — APPROVED** [review]
If we can have additional feedback before releasing v4, then we update here 🤷

**Pull request merged**
