### PR TITLE
fix(ruleset scoring and tagging): Fix PL related issues in v3.3./dev

### PR DESCRIPTION
**Pull request by airween**
This PR collects few small commits, see the messages at the commits.

### CODE REVIEW

**Comment by airween** [comment]
Uhm, can someone check the docker image?

The [error message](https://github.com/coreruleset/coreruleset/actions/runs/3352741133/jobs/5555083456#step:6:2439) in the test:

```
==================================== ERRORS ====================================
_____________ ERROR at setup of test_crs[941330.yaml -- 941330-1] ______________
tests/regression/CRS_Tests.py:100: in logchecker_obj
    return FooLogChecker(config)
tests/regression/CRS_Tests.py:19: in __init__
    self.backwards_reader = BackwardsReader(self.log_location)
tests/regression/CRS_Tests.py:109: in __init__
    self.f = open(file, 'rb')
E   FileNotFoundError: [Errno 2] No such file or directory: 'tests/logs/modsec2-apache/error.log'
```

Note, that this PR belongs to v3.3/dev.

**Comment by theseion** [comment]
You have a duplicate rule id in the initialization file: 901169.

**Comment by airween** [comment]
> You have a duplicate rule id in the initialization file: 901169.

Damn it... Thanks, of course. Btw, 901168 was also duplicated. I've added a new method to `rules-check.py` script to avoid this.

**Comment by airween** [comment]
@lifeforms, I reviewed v3.3/dev, this PR contains some cosmetic fixes. After we approved it, we can take a look to #2891, and I think then the 3.3 will be ready for the final release.

**Comment by airween** [comment]
@lifeforms: please do not merge it into v3.3/master, I've found an Nginx related issue. I will let you know when I fixed that.

**Pull request merged**
