### PR TITLE
fix(sqli): additional regular expressions for SQL auth bypass

### PR DESCRIPTION
**Pull request by karelorigin**
This PR contains new regular expressions for different kinds of auth bypasses. In an ideal world, these would be inside the operator dataset, but unfortunately, they look too much like normal sentences to accurately block.

Edit:
 * Contains fixes to bypasses found by me (`DV2UKLP4`, `2AUWUOVF`, `RICGZH4Q`)
 * Contains fixes to bypasses found by @wfinn (`YPWZU6PD` and `Q6FBUFOD`)

### CODE REVIEW

**Comment by azurit** [comment]
Hi @karelorigin , thanks for sending this!

**Comment by karelorigin** [comment]
Hi!

This PR should also be able to catch a NoSQL bypass reported by @hussein98d in `RQ1R4RCP`, except that it's not evaluated on the URL path. Is this something I could add?

**Comment by dune73** [comment]
This also covers `DV2UKLP4`

**Comment by karelorigin** [comment]
Hi @dune73, I've updated my original comment to better outline the reports this PR applies to. That should be the complete list of reports relevant to this PR.

**Comment by dune73** [comment]
Thank you. We'll get to the question of `RQ1R4RCP` during the review.

**Comment by dune73** [comment]
### CRS Bug Bounty PR assessment

* **Rules affected** (list rules): FIXME
* **Paranoia Level addressed** (1, 2, 3, 4, full or explain): FIXME
* **FTW passes** (yes or no) : FIXME
* **Rule(s) picked for solution** (correct or not-correct or explain) : FIXME
* **Risk for false positives** (irrelevant, adequate, substantial or explain) : FIXME
* **Regular expression quality** (inspirational, decent base, needs work, adequate or explain) : FIXME
* **Documentation** (needs work, adequate or explain) : FIXME
* **Tests** (none or some or adequate) : FIXME
&nbsp;
* **Verdict** (Unusable, inspirational, usable, almost perfect or perfect) : FIXME

_This is not meant to be final. As a CRS dev, feel free to comment below and edit this form directly. As committer or observer, feel free to comment below with feedback and we will think about updating the assessment accordingly._

**Comment by fzipi** [comment]
CRS TODO: add a comment on file util/regexp-assemble/data/942340.data line 43-47 on why are those there, so documentation is in one file (we can't ask this in this PR, wasn't agreed in the first place).

**Comment by fzipi** [comment]
Hi @karelorigin !

Inevitably, we run onto conflicts after we started merging. Can you help us resolve this one?

**Comment by karelorigin** [comment]
Hey @fzipi, yeah for sure! I could rebase but that rewrites git history and will probably create a mess, so I'll try to do it via the GitHub interface. Will work on it as soon as I get the chance (might take a couple of days)

**Comment by lifeforms** [comment]
Hi @karelorigin, there seem to be still some odd conflicts, could you solve them or do you need help?

**Comment by karelorigin** [comment]
@lifeforms, I've been super busy but I'll get on this ASAP. I should be able to resolve them just fine but I'll definitely ask for help if I need it. Sorry about that!

**Comment by karelorigin** [comment]
Resolved all conflicts, should be fine merging this now :)

**Comment by fzipi** [comment]
Looks awesome! Thanks @karelorigin for this PR! 🎉

**Pull request merged**
