### PR TITLE
Moved --> keyword from 941180 (PL1) into new stricter sibling rule 941181 (PL2)

### PR DESCRIPTION
**Pull request by 53cur3M3**
Fix for False Positive #2060, at paranoia level 1, caused by matching of "-->".
Moved --> keyword from 941180 (PL1) into new stricter sibling rule 941181 (PL2)

### CODE REVIEW

**Comment by dune73** [comment]
Cool. Thank you for your contribution.

Would you mind creating a test or two for 941181? See the stuff in `tests/regression`.

Happy to merge afterwards.

**Comment by dune73** [comment]
@fzipi it looks like lint does not like `contains` or `-->` very much. The test failed. Would you mind taking a peek?

**Comment by airween** [comment]
> @fzipi it looks like lint does not like `contains` or `-->` very much. The test failed. Would you mind taking a peek?

[PR](https://github.com/coreruleset/secrules_parsing/pull/17) has sent :).

**Comment by azurit** [comment]
I think you should remove `blacklist` keyword replacement until issue https://github.com/coreruleset/coreruleset/issues/2083 is discussed.

**Comment by dune73** [comment]
In the spirit of keeping things separate, I agree with @azurit that this PR should only do the rules split, now that we have a separate issue and a PR to implement this shift.

**Comment by dune73** [comment]
Following the merging of [secrules_parsing PR 17](https://github.com/coreruleset/secrules_parsing/pull/17) we seem to have a new regression with lint on the Webshells response rules. 

@airween and @fzipi, could you please check this?

**Comment by dune73** [comment]
So we're fine with regards to lint again. Thank you for the quick reaction, @airween and @fzipi.

**Comment by 53cur3M3** [comment]
Replaced by pull request 2088

**Pull request closed without merging**
