### PR TITLE
Sqli remove unnecessary lazy quantifiers

### PR DESCRIPTION
**Pull request by theseion**
Split from #2290.

The intention of this PR is to complete the work from #2290 w.r.t. removing unnecessary lazy quantifiers. In particular, sequences such as `...\s*?` cause more backtracking than the semantically equivalent `...\s*`.

### CODE REVIEW

**Comment by franbuehler** [comment]
Meeting decision [April chat meeting](https://github.com/coreruleset/coreruleset/issues/2453#issuecomment-1087887351): 
We postpone the thorough review for after 4.0. It's unclear what the performance impacts are and changing lazy to greedy isn't without risks

**Comment by dune73** [comment]
I am no longer sure how to interprete teh April chat decision. I think it means we postpone the merging of this PR as well. If not, we need somebody to push it forward.

**Comment by theseion** [comment]
Yes, postponed till after v4.

**Comment by dune73** [comment]
@theseion should we plan to bring this back to life or has it been superseded by so many other changes?

**Comment by theseion** [comment]
Should still be valid, but the PR will definitely have to be redone.

**Comment by dune73** [comment]
I see that. But it kind of feels like a welcome cleanup, does not it? Maybe we find a volunteer to do it.

**Comment by theseion** [comment]
Sure.

**Pull request closed without merging**
