### PR TITLE
Remove IP reputation rules.

### PR DESCRIPTION
**Pull request by studersi**
This PR is intended to address https://github.com/coreruleset/coreruleset/issues/2433.

This PR removes the IP reputation rules from CRS. The IP reputation rules include
* all rules in `REQUEST-910-IP-REPUTATION.conf`, which include
  * skips for quicker blocking of requests from IPs with bad reputation,
  * anomaly scoring and reputation flagging based on GeoIP lookups, and
  * reputation flagging based on RBL lookups, as well as
* rule `949100` which performs `deny` actions for request with the persistent variable `IP:REPUT_BLOCK_FLAG` set,
* custom variables set in `REQUEST-913-SCANNER-DETECTION.conf` to flag IPs that are identified as scanners, and
* any associated configurations in `crs-setup.conf.example`, such as configurations for
  * Project Honey Pot HTTP (RBL lookups),
  * reputation flagging based on GeoIP databases and the provided country codes,
  * blocking based on IP reputation, and
  * comments in the description of collection timeouts related to IP reputation blocking.

### CODE REVIEW

**Comment by studersi** [comment]
@dune73 FYI

**Comment by dune73** [comment]
Looks good to me. I have tested this and I think the rest of CRS still works. As confirmed by the tests as well.

Also looked through the files and I no longer see any reference to the IP reputation in question.

Given we do not have plugin functionality to replace this just yet, I do not want to merge without further consultation, but I am positive to merge PR as is and provide plugins later (Depending on functionality probably not at all).

**Comment by fzipi** [comment]
While I see this as a plugin, IP reputation and Geo can be thought as different problems. Maybe I want to block anything coming from `.uy` or `.ch`. Even anything coming from Europe. Or just limit this application to only my country instead.

Conceptually, they should come from different inputs: ip reputation should be from RBL lists, or can be based on indicators of compromise or any Threat Intelligence resource. It is more dynamic in essence. An geoip from the geoip database.

We are kind of removing both here.

So I think that rule 910100 should be kept separately from this. Maybe rewritten and remove anything related to reputation?

Or we just remove anything related to both cases, and move them into *two* different plugins?

**Comment by dune73** [comment]
I'd opt to remove both and create two separate plugins. As it happens I started to re-visit GeoIP for ModSec2 again, namely because MaxMind is chanding free access to their databases etc.

Here are my notes just in case:

```
GeoIP / mod_maxminddb

        -> https://github.com/maxmind/mod_maxminddb

        $ sudo apt-get install libmaxminddb0
        $ sudo apt-get install libmaxminddb-dev 
        $ sudo apt-get install geoipupdate 
        $ wget https://github.com/maxmind/mod_maxminddb/releases/download/1.2.0/mod_maxminddb-1.2.0.tar.gz
        $ tar xvzf mod_maxminddb-1.2.0.tar.gz 
        $ cd mod_maxminddb-1.2.0/
        $ ./configure --with-apxs=/apache/bin/apxs
        $ make
        $ sudo make install
        $ laltr /apache/modules/
        $       -> mod_maxminddb.so

        Apache Configuration


        LoadModule maxminddb_module modules/mod_maxminddb.so

        MaxMindDBEnable On

        MaxMindDBFile   COUNTRY_DB              /usr/share/GeoIP/GeoLite2-Country.mmdb
        MaxMindDBEnv    GEOIP_COUNTRY_CODE      COUNTRY_DB/country/iso_code

        Getting the GeoLite2 database is really difficult these days.

        There is a script / package named geoipupdate 
                it takes a license key that can be generated on the maxmind website.

        Installation of script
                 $ sudo add-apt-repository ppa:maxmind/ppa
                 $ sudo apt-get install geoipupdate
                 $ cat > /etc/GeoIP.conf

                        # GeoIP.conf file for `geoipupdate` program, for versions >= 3.1.1.
                        # Used to update GeoIP databases from https://www.maxmind.com.
                        # For more information about this config file, visit the docs at
                        # https://dev.maxmind.com/geoip/updating-databases?lang=en.

                        # AccountID is from your MaxMind account.
                        AccountID xxxxxx

                        # LicenseKey is from your MaxMind account
                        LicenseKey xxxxxx

                        # EditionIDs is from your MaxMind account.
                        EditionIDs GeoLite2-Country

        run:
                $ sudo gepipupdate -v

                DB saved per default in /usr/share/GeoIP

        ModSec integration

                By default, mod_maxminddb runs on the same hook as ModSec phase 1, but
                it runs after modsec. In order to make sure the geoip env variable is
                available for ModSec phase 1, ModSec has to be patched.


                        $ diff -c apache2/mod_security2.c apache2/mod_security2.c-new
                        *** apache2/mod_security2.c     2022-04-03 20:04:12.176397848 +0200
                        --- apache2/mod_security2.c-new 2022-04-03 20:03:42.360440868 +0200
                        ***************
                        *** 1668,1673 ****
                        --- 1668,1674 ----
                                  "mod_breach_realip.c",
                                  "mod_breach_trans.c",
                                  "mod_unique_id.c",
                        +         "mod_maxminddb.c",
                                  NULL
                              };
                          
                If this is not done, the GeoIP env var can be used in phase 2 and it will be in the
                log file, but it is not available in phase 1.

                Afterwards, GeoIP can be used as follows

                        SecRule ENV:GEOIP_COUNTRY_CODE    "."  "id:1005,phase:1,pass,log,msg:'GeoIP phase 1 %{MATCHED_VAR}'"

                        SecRule ENV:GEOIP_COUNTRY_CODE    "."  "id:1006,phase:2,pass,log,msg:'GeoIP phase 2 %{MATCHED_VAR}'"



```

**Comment by dune73** [comment]
If we agree on this approach, I think this could be merged as is.

**Comment by RedXanadu** [comment]
To add to the MaxMind conversation, emphazer has a great script that converts a new-style MaxMind database file into an old-style .dat file which can be plugged directly into ModSecurity using `SecGeoLookupDb`:
https://github.com/emphazer/GeoIP_convert-v2-v1/

I don't know if that's simpler or easier than using `mod_maxminddb`, which I never knew existed!

**Comment by fzipi** [comment]
I don't think you need the apache module. Unless you have other uses for it, you can just use modsecurity. In https://github.com/coreruleset/coreruleset/issues/1584 I've updated the text in the crs-setup.conf.example and that is exactly what you need.

MaxMind needed to change because the CCPA regulation. So now you need to register (for free) to download their databases.

**Comment by dune73** [comment]
I think it is good to have multiple options here.

True, I forgot we have the proper description in the setup.conf, but I still think said transformation is a hack.

Working with the official module / script is therefore an option from my point of view and I think we should document / allow for both. Which is easy anyways.

**Comment by dune73** [comment]
Ready to merge this one here?

**Comment by studersi** [comment]
Rebased to fix conflicts.

**Pull request merged**
