### PR TITLE
Added additional SQL function signatures

### PR DESCRIPTION
**Pull request by karelorigin**
The `likelihood` function was originally found and reported by @hussein98d in `ELRK4163`. However, I've added extra functions that were also able to bypass the SQL rules.

### CODE REVIEW

**Comment by dune73** [comment]
### CRS Bug Bounty PR assessment

* **Rules affected** (list rules): FIXME
* **Paranoia Level addressed** (1, 2, 3, 4, full or explain): FIXME
* **FTW passes** (yes or no) : FIXME
* **Rule(s) picked for solution** (correct or not-correct or explain) : FIXME
* **Risk for false positives** (irrelevant, adequate, substantial or explain) : FIXME
* **Regular expression quality** (inspirational, decent base, needs work, adequate or explain) : FIXME
* **Documentation** (needs work, adequate or explain) : FIXME
* **Tests** (none or some or adequate) : FIXME
&nbsp;
* **Verdict** (Unusable, inspirational, usable, almost perfect or perfect) : FIXME

_This is not meant to be final. As a CRS dev, feel free to comment below and edit this form directly. As committer or observer, feel free to comment below with feedback and we will think about updating the assessment accordingly._

**Comment by lifeforms** [comment]
@karelorigin The SQLite documentation mentions quite a number of other JSON functions, did you check these? Or did you decide that they are not usable? https://www.sqlite.org/json1.html

**Comment by lifeforms** [comment]
Will `json (` not give us too many false positives? Maybe it could be moved to a higher PL.

**Comment by karelorigin** [comment]
@lifeforms, I actually took them from that exact source. Not all of them are in there but not all of them are usable as you correctly guessed.  These additions shouldn't be that much different from the entries that were already in there. Certain math functions are also common in regular speech or even math: `ceil`, `cos`, etc.

**Comment by lifeforms** [comment]
We're going to try it out! Thanks for the PR!

**Pull request merged**
