### PR TITLE
Added new nextcloud excludes for the "Security & setup warnings" test and session tokens

### PR DESCRIPTION
**Pull request by ntimo**
This fixes the "Security & setup warnings" test in the overview section of the nextcloud administrator settings. This also fixes the security session revocation being blocked. And the deletion of notifications.

### CODE REVIEW

**Comment by fzipi** [comment]
Hi @ntimo ! Thanks for your contribution, looks awesome!.

I see you added the conditions `@streq /.well-known/caldav` and `@streq /.well-known/carddav`. What happens if the nextcloud install is in a subdirectory, instead of `/` (mine is in `/nextcloud`, for example). Do you think maybe using `@endsWith` or `@contains` is better in that case?

**Comment by ntimo** [comment]
Sure, I will change it it contains probably.

**Comment by ntimo** [comment]
@fzipi done

**Comment by fzipi** [comment]
@ntimo :thinking: Instead of removing 911100, why don't you add the corresponding methods to the list?

Like we do in the same file, rule 9003140:
```
SecRule REQUEST_FILENAME "@rx /ocs/v[0-9]+\.php/apps/files_sharing/" \
    "id:9003140,\
    phase:2,\
    pass,\
    t:none,\
    nolog,\
    ver:'OWASP_CRS/3.3.0',\
    setvar:'tx.allowed_methods=%{tx.allowed_methods} PUT DELETE'"
```

This way we don't need chaining rules, and looks cleaner. What do you think?

**Comment by fzipi** [comment]
@ntimo What do you think on this?

**Comment by ntimo** [comment]
Sure sound like a very good idea. I will change the PR @fzipi

**Comment by fzipi** [comment]
@ntimo Did you had time to test this new approach? Can you provide us with the new PR? :smiley:

**Comment by dune73** [comment]
Any update on the status here, @ntimo?

**Comment by franbuehler** [comment]
Monthly Meeting September: https://github.com/coreruleset/coreruleset/issues/1869#issuecomment-688474359
@fzipi takes this PR.

**Comment by fzipi** [comment]
Superseded by #1878 .

**Pull request closed without merging**
