### PR TITLE
Added some unix shell

### PR DESCRIPTION
**Pull request by gwen001**
Report: `ANQ9SN3S` let say

```
usr/bin/at
usr/bin/cpulimit
usr/bin/flock
usr/bin/gdb
usr/bin/man
usr/bin/rvim
usr/bin/vi
usr/bin/vim
```

I'm still working on a bigger list, but I was able to confirm those ones.

Source: https://gtfobins.github.io/#+shell

### CODE REVIEW

**Comment by gwen001** [comment]
```
bin/busybox
bin/composer
bin/cpio
bin/ed
bin/journalctl
bin/loginctl
bin/nano
bin/run-parts
bin/sed
bin/tar
sbin/capsh
sbin/logsave
sbin/start-stop-daemon
usr/bin/apt
usr/bin/apt-get
usr/bin/bundler
usr/bin/busctl
usr/bin/c89
usr/bin/c99
usr/bin/certbot
usr/bin/cpan
usr/bin/dpkg
usr/bin/emacs
usr/bin/ex
usr/bin/expect
usr/bin/gcc
usr/bin/gem
usr/bin/git
usr/bin/ionice
usr/bin/irb
usr/bin/ltrace
usr/bin/make
usr/bin/mawk
usr/bin/mysql
usr/bin/nawk
usr/bin/node
usr/bin/nohup
usr/bin/nroff
usr/bin/nsenter
usr/bin/pdb
usr/bin/pic
usr/bin/pico
usr/bin/rake
usr/bin/rsync
usr/bin/run-mailcap
usr/bin/rview
usr/bin/scp
usr/bin/screen
usr/bin/script
usr/bin/setarch
usr/bin/sftp
usr/bin/sg
usr/bin/split
usr/bin/sqlite3
usr/bin/ssh
usr/bin/stdbuf
usr/bin/strace
usr/bin/taskset
usr/bin/time
usr/bin/timedatectl
usr/bin/timeout
usr/bin/tmux
usr/bin/unshare
usr/bin/view
usr/bin/vimdiff
usr/bin/watch
usr/bin/zip
usr/local/bin/easy_install
usr/local/bin/npm
usr/local/bin/pip
usr/sbin/service
```

**Comment by gwen001** [comment]
These have also been added in PR https://github.com/coreruleset/coreruleset/pull/2552 by @wfinn

**Comment by dune73** [comment]
### CRS Bug Bounty PR assessment

* **Rules affected** (list rules): FIXME
* **Paranoia Level addressed** (1, 2, 3, 4, full or explain): FIXME
* **FTW passes** (yes or no) : FIXME
* **Rule(s) picked for solution** (correct or not-correct or explain) : FIXME
* **Risk for false positives** (irrelevant, adequate, substantial or explain) : FIXME
* **Regular expression quality** (inspirational, decent base, needs work, adequate or explain) : FIXME
* **Documentation** (needs work, adequate or explain) : FIXME
* **Tests** (none or some or adequate) : FIXME
&nbsp;
* **Verdict** (Unusable, inspirational, usable, almost perfect or perfect) : FIXME

_This is not meant to be final. As a CRS dev, feel free to comment below and edit this form directly. As committer or observer, feel free to comment below with feedback and we will think about updating the assessment accordingly._

**Comment by gwen001** [comment]
Since the workflow failed because of a Lint syntax error, I added a new line at the end of the file.
Not sure this will save us...

**Comment by RedXanadu** [comment]
@gwen001 That did the trick. Thank you!

**Comment by lifeforms** [comment]
Thanks for the help!

**Pull request merged**
