### PR TITLE
Fix 933210 Regex

### PR DESCRIPTION
**Pull request by theMiddleBlue**
as discussed in the coreruleset-dev slack channel.
I'm intentionally not sharing other information.

### CODE REVIEW

**Comment by dune73** [comment]
You marked this as a draft. Please let us know, when you are ready.

**Comment by theMiddleBlue** [comment]
there're two complete different situation on apache and nginx... I'm trying this PR on my local sandbox

nginx works as expected:
```shell
curl -s -H 'x-backend: nginx-test' -H 'x-format-output: txt-matched-rules' "http://localhost/?code=%22system%22%28ls%29%3B"
```

```
933210 PL1 PHP Injection Attack: Variable Function Call Found
949110 PL1 Inbound Anomaly Score Exceeded (Total Score: 5)
```

Apache not:
```shell
curl -s -H 'x-backend: apache-test' -H 'x-format-output: txt-matched-rules' "http://localhost/?code=%22system%22%28ls%29%3B"
```
```shell
100000 PL1 No rules matched
```

can be related to escape sequences like `\\` ? any ideas?

**Comment by theMiddleBlue** [comment]
solved with \x5c

**Comment by franbuehler** [comment]
[Meeting decision December](https://github.com/coreruleset/coreruleset/issues/2291#issuecomment-987122691): we wait with this PR until @theMiddleBlue has time to comment.

**Comment by theMiddleBlue** [comment]
yep, this can be merged IMO

**Comment by fzipi** [comment]
Merging then!

**Comment by fzipi** [comment]
Just as a last comment, I would like to see this one "decompiled" if we can.

**Pull request merged**
