### PR TITLE
Fix false negative in rule 920480

### PR DESCRIPTION
**Pull request by fgsch**
Unfortunately this requires a backwards incompatible change, similar to what was applied to rule 920420.

### CODE REVIEW

**Comment by dune73** [comment]
"Partial matching" as `iso-8859-1` being a partial match of `iso-8859-15`? That's a problem, yes.

Could you describe what you are doing exactly? Maybe also in the PR?

I think I got it - really cunning - but maybe not too the full extent.

**Comment by fgsch** [comment]
@dune73 I've expanded the commit message to further explain the issue (copied below for convenience). 
Let me know if this answers your question.

```
he problem lies in the inner rule. The operation was
"!@rx ^%{tx.allowed_request_content_type_charset}$", which was
expanded to "^utf-8|iso-8859-1|iso-8859-15|windows-1252$".

The pattern is anchored (^..$) but the anchors only apply to the
first and last alternative, "utf-8" and "windows-1252", respectively,
and not the entire pattern as it lacks the surrounding parenthesis.
This means that "utf-88", "iso-8859-10" or "foo-windows-1252" are
considered valid.

Unfortunately is not possible to just add the parenthesis as
ModSecurity will escape them when resolving the macro.
This solution follows the approach done for 920420, changing the
macro's content format and using @within, making this a
backwards-incompatible change.
```

**Comment by dune73** [comment]
Thank you very much. Splendid.

**Comment by dune73** [comment]
[Meeting decision monthly chat Jan 2020](https://github.com/coreruleset/coreruleset/issues/1953#issuecomment-754192936):

@dune73 will review this.

**Comment by dune73** [comment]
Thank you for the PR and the extended comment above. Crystal clear now.

I have tested this PR and reviewed it. It does what it intends to do.

I suggest to add the following sentence to the crs-setup.conf.example (right before the line starting with `Default:`):

`# The content-types are enclosed by |pipes| as delimiters to guarantee exact matches.`

The PR is ready to be merged afterwards.

But here is a thought: If you look through crs-setup.conf.example, there are several variables that use double-anything as delimiter:

tx.allowed_request_content_type : pipes
tx.allowed_http_versions: slashes
tx.restricted_extensions: slashes (single)
tx.restricted_headers: slashes
tx.allowed_request_content_type_charset: pipes (new)

I did not pay attention, when we went from rx to within for the rule using tx.allowed_request_content_type, but I get the feeling it would be beneficial to consolidate this all onto the same delimiter for 3.4.

If you agree, we can merge this an open a new issue for that idea.

**Comment by fgsch** [comment]
Updated.

**Comment by fgsch** [comment]
Regarding consolidating the various delimiters, it might not be possible to use something sensible since different headers might need to use different delimiters, but definitely something we can take a look at.

**Comment by dune73** [comment]
Thank you for the fix and shoot-out to @katef for spotting this.

Merging now.

**Pull request merged**
