### PR TITLE
Fixed assembly of 920120-no-backtracking.data

### PR DESCRIPTION
**Pull request by theseion**

### CODE REVIEW

**Comment by fzipi** [comment]
Just to have it in one place, the target of this rule is:
```
# 920120: PL1 : FILES_NAMES, FILES
#                ['\";=] but allowed:
#                &[aAoOuUyY]uml); &[aAeEiIoOuU]circ; &[eEiIoOuUyY]acute;
#                &[aAeEiIoOuU]grave; &[cC]cedil; &[aAnNoO]tilde; &amp; &apos;
```

**Review by fzipi — CHANGES_REQUESTED** [review]
I've added the intention on this rule to get a collective view into this one.

First, and not related, the 920120.data looks like the regexp [is not "disassembled"](https://github.com/coreruleset/coreruleset/blob/5945066048cc8d4351af3600b4211a0e4d1e1224/util/regexp-assemble/data/920120.data#L25). So it is a bit difficult to compare.

Regarding the new one, looks like `aacute` was left out in line 37. It should be `&[aeEiIoOuUyY]acute`. I'm going to review all these html metas so see if we are missing others, just in case. BTW, it is out also in the original no backtracking data file....

Other than that, my test for just `file` works as it is not matching now. Will create a new issue to track changes in 920120 in general.

**Comment by theseion** [comment]
Not sure it helps, but I've properly disassembled 920120.

**Comment by theseion** [comment]
Just learned something new: lookbehind assertions must be of fixed length. That even means that you can't use certain grouping patterns, so we can't use regexp-assemble.py to assemble the individual branches inside of the lookbehind assertion.

**Comment by theseion** [comment]
You're right about `aacute`. If we're messing around with the role, I feel we could also just make it case insensitive instead of listing lower and uppercase variants in the character classes.

**Comment by fzipi** [comment]
Also, take a look at the linked issue.

**Comment by fzipi** [comment]
@theseion With the extended html entities, and using case ignore this is what I get:
```
##!+ i

##!> neglook
&[aeiouy]uml;
&[aeioucghjswy]circ;
&[aeiouclnrszg]acute;
&[aeiou]grave;
&[cgklnrst]cedil;
&[anoi]tilde;
&[cdelnrstz]caron;
&oslash;
&amp;
&apos;
&[au]ring;
##!<

##!$ ;|['\"=]
```

What do you think?

**Comment by franbuehler** [comment]
[Meeting decision January](https://github.com/coreruleset/coreruleset/issues/2330#issuecomment-1004310622): @franbuehler volunteered to review it but just saw that @fzipi is already reviewing it...

**Comment by theseion** [comment]
Responding to the question in chat: the line `##!$ ;|['\"=]` is a suffix comment. This will append `;|['\"=]` to the end of the regex. If we didn't mark this as a suffix, `;|['\"=]` would be added as a branch instead (`...;|['\"=]` vs. `...|;|['\"=]`).

**Comment by theseion** [comment]
@fzipi I've updated the data files and the rule comment with your suggestion. I noticed that you've added a couple more entities and I was wondering about the rational. The rule comment says that "common" entities are allowed but I'm not sure what would be considered common. I'd also include `&nbsp;` in the list of common entities. Do you  have a better idea for which entities to includes than just "common"?

**Comment by theseion** [comment]
@fzipi pint

**Comment by fzipi** [comment]
@theseion I just added all the entities that could be used in a file name.... probably adding `&nbsp;` might help.

**Comment by theseion** [comment]
@fzipi Can you run your test once more on the latest commit?

**Comment by fzipi** [comment]
Yes, all tests look good using the generating using no-backtracking data:
```
(?i)(?:(?:^|[^enlcgpsh])|(?:^|[^tvd])e|(?:^|[^o])n|(?:^|[^im])l|(?:^|[^r])c|(?:^|[^n])g|(?:^|[^ms])p|(?:^|[^o])s|(?:^|[^s])h|(?:^|[^u])te|(?:^|[^r])on|(?:^|[^d])il|(?:^|[^i])rc|(?:^|[^a])ve|(?:^|[^i])ng|(?:^|[^l])de|(?:^|[^u])ml|(?:^|[^a])mp|(?:^|[^p])os|(?:^|[^b])sp|(?:^|[^a])sh|(?:^|[^c])ute|(?:^|[^a])ron|(?:^|[^e])dil|(?:^|[^c])irc|(?:^|[^r])ave|(?:^|[^r])ing|(?:^|[^i])lde|(?:^|[^aeiouy])uml|(?:^|[^&])amp|(?:^|[^a])pos|(?:^|[^n])bsp|(?:^|[^l])ash|(?:^|[^a])cute|(?:^|[^c])aron|(?:^|[^c])edil|(?:^|[^aeioucghjswy])circ|(?:^|[^g])rave|(?:^|[^au])ring|(?:^|[^t])ilde|(?:^|[^&])[aeiouy]uml|(?:^|[^&])apos|(?:^|[^&])nbsp|(?:^|[^s])lash|(?:^|[^aeiouclnrszg])acute|(?:^|[^cdelnrstz])caron|(?:^|[^cgklnrst])cedil|(?:^|[^&])[aeioucghjswy]circ|(?:^|[^aeiou])grave|(?:^|[^&])[au]ring|(?:^|[^anoi])tilde|(?:^|[^o])slash|(?:^|[^&])[aeiouclnrszg]acute|(?:^|[^&])[cdelnrstz]caron|(?:^|[^&])[cgklnrst]cedil|(?:^|[^&])[aeiou]grave|(?:^|[^&])[anoi]tilde|(?:^|[^&])oslash);|['\"=]
```

Tests:
```
❯ ./ftw run -d tests -i ^920120
1:21PM INF ftw/config: no duration found
1:21PM INF 🛠️  Starting tests!

🚀 Running go-ftw!
👉 executing tests in file 920120.yaml
	running 920120-1: ✔ passed in 109.261559ms
	running 920120-2: ✔ passed in 1.051451432s
	running 920120-3: ✔ passed in 123.82658ms
	running 920120-4: ✔ passed in 81.976114ms
	running 920120-5: ✔ passed in 93.73251ms
	running 920120-6: ✔ passed in 93.490047ms
	running 920120-7: ✔ passed in 103.964909ms
	running 920120-8: ✔ passed in 96.080811ms
	running 920120-9: ✔ passed in 93.157169ms
	running 920120-10: ✔ passed in 100.846706ms
	running 920120-11: ✔ passed in 110.68612ms
	running 920120-12: ✔ passed in 102.233191ms
	running 920120-13: ✔ passed in 94.317103ms
	running 920120-14: ✔ passed in 92.950227ms
	running 920120-15: ✔ passed in 90.528696ms
	running 920120-16: ✔ passed in 92.780996ms
	running 920120-17: ✔ passed in 95.518904ms
	running 920120-18: ✔ passed in 93.303631ms
	running 920120-19: ✔ passed in 98.386815ms
	running 920120-20: ✔ passed in 89.70153ms
	running 920120-21: ✔ passed in 91.733384ms
➕ run 21 total tests in 2.999928434s
⏭  skept 2586 tests
🎉 All tests successful!
```

**Comment by theseion** [comment]
I've added tests for all of the entities (including variants). Tests are green. From my point of view this is ready merge. @fzipi?

**Comment by fzipi** [comment]
Agreed, merging.

**Pull request merged**
