### PR TITLE
Add entry for c99 and printf utilities (932150)

### PR DESCRIPTION
**Pull request by karelorigin**
This PR contains fixes to bypasses that were originally found and reported by @hussein98d in `3G2QSW2D` and `BXV8FILT`.

### CODE REVIEW

**Comment by RedXanadu** [comment]
Hi @karelorigin, could we get the updated `.data` file used to generate the new regular expression pattern, please? :slightly_smiling_face:

**Comment by RedXanadu** [comment]
Ah, I think you've included the `.data` file update in this other PR: #2570 

Is that right? If so, could you update it here instead, to keep the commits together in a logical way?

**Comment by karelorigin** [comment]
Crap, I definitely messed something up. Was a bit tricky since regexp-assemble.py only worked if I commented out a certain line, which I didn't want to commit. So instead of manually removing the comment each time I tried only staging the files I changed. Obviously that went wrong 😅

I'll fix it asap

**Comment by karelorigin** [comment]
Done! Added the changes to this PR and removed them from #2570 @RedXanadu

**Comment by RedXanadu** [comment]
@karelorigin Great stuff, thanks. I think we have everything we need here, now.

**Comment by karelorigin** [comment]
Great! I just hope I didn't make the same mistake anywhere else

**Comment by lifeforms** [comment]
Merged, thank you!

**Pull request merged**
