### PR TITLE
feat(lint): check for combinations of t:lowercase and (?i)

### PR DESCRIPTION
**Pull request by franbuehler**
This PR solves #3579.

This is my first try to extend the linting or the [rules-check.py](https://github.com/coreruleset/coreruleset/blob/main/util/crs-rules-check/rules-check.py). I'm open for feedback.

Btw: 3 rules use both the `t:lowercase` and the `(?i)` flag in the regex.

What do you think @theseion or @airween?

### CODE REVIEW

**Review by airween — DISMISSED** [review]
Could you add an example file into [examples](https://github.com/coreruleset/coreruleset/tree/main/util/crs-rules-check/examples) directory?

And please add this new stop to [documentation](https://github.com/coreruleset/coreruleset/tree/main/util/crs-rules-check#how-does-it-work) and the example usage to [examples](https://github.com/coreruleset/coreruleset/tree/main/util/crs-rules-check#examples) section.

Thanks!

**Comment by airween** [comment]
Hi @franbuehler,

many thanks for this PR, it seems good to me. I added few remarks to it, please take a look at my review.

> Btw: 3 rules use both the `t:lowercase` and the `(?i)` flag in the regex.

yes, this shows the new feature works as well! :)

And before to merge this we need to fix the 3 affected issues.

**Comment by franbuehler** [comment]
Thank you for your review and the issue removing the `t:lowercase`, @airween.
I'll work on this PR tomorrow.

**Comment by airween** [comment]
> Thank you for your review and the PR removing the `t:lowercase`, @airween. I'll work on my PR tomorrow.

Please pick up the changes from main by #3585. After that the check-syntax script will be successfull.

**Review by airween — APPROVED** [review]
Excellent! Thank you!

**Pull request merged**
