### PR TITLE
fix(bb-681L2A1M): add node.js child_process injection

### PR DESCRIPTION
**Pull request by theMiddleBlue**
Node.js rules don't match on `child_process` injection.

This PR:

- adds `\(\s*\Wchild_process\W\s*\)\s*\W\s*exec\s*\(` to 934100.data
- adds `require\s*\(` to 934101.data
- adds `REQUEST_FILENAME` on both 934100 and 934101

### CODE REVIEW

**Comment by theMiddleBlue** [comment]
I checked on the sandbox, and it seems all reported payloads match now.
can anyone review this?

**Review by dune73 — COMMENTED** [review]
I suggest to reduce the regex pattern to
```
\(\s*\Wchild_process\W\s*\)
```

Otherwise, this seems good to go.

**Comment by theMiddleBlue** [comment]
done

**Comment by dune73** [comment]
Ready to merge then. Thank you @theMiddleBlue.

**Pull request merged**
