### PR TITLE
Web shells: Huge update

### PR DESCRIPTION
**Pull request by azurit**
Adding support for **60** new web shells (PHP). We are now able to detect 95 web shells.

Data source: https://github.com/JohnTroony/php-webshells/tree/master/Collection

### CODE REVIEW

**Comment by azurit** [comment]
Maybe i should renumber rule IDs and assign IDs with step of 5 instead of 10? Currently, the last rule has ID 955960.

**Comment by dune73** [comment]
You're on fire man!

This is a great contribution. We will need to talk about the right form to introduce this. As it stands it's an awful lot of rules and that means a severe performance impact.

**Comment by azurit** [comment]
Lots of rules (those not using `@rx`) could be joined togather using `@pm`.

**Comment by dune73** [comment]
That's what I thought as well. :)

**Comment by azurit** [comment]
See https://github.com/coreruleset/coreruleset/pull/2116

**Comment by dune73** [comment]
Closing this PR in favor of PR #2116.

**Pull request closed without merging**
