### PR TITLE
Improve sampling efficiency2

### PR DESCRIPTION
**Pull request by 53cur3M3**
Simplify sampling rules, and improve efficiency, as per : https://github.com/coreruleset/coreruleset/issues/2091
Tested in apache modsec2, but requires testing in modsec3 to validate leading zeros are handled gracefully; and preferably also what happens if TX.sampling_rnd100 is undefined

### CODE REVIEW

**Comment by azurit** [comment]
Looks good to me. Maybe @airween can test modsec 3 compatiblity? :smile:

**Comment by dune73** [comment]
We need somebody to test this for ModSec3. If these tests pass, the conflict with 901 has to be resolved, afterwards, we are ready to merge.

Tests for ModSec3:
* Do we get roughly 50:50 CRS execution when the the sampling rate is set to 50%
* Does ModSec3 handle leading 0s in `TX.sampling_rnd100` gracefully (e.g.: `04` should be handled identically to `4`)

**Comment by franbuehler** [comment]
Meeting decision June (https://github.com/coreruleset/coreruleset/issues/2074#issuecomment-856173925):
@theMiddleBlue will review this PR.

**Comment by dune73** [comment]
Hey @theMiddleBlue did you have time to test this on ModSec3? If yes, we would like to merge this. Ideally before the chat on Monday.

**Comment by dune73** [comment]
Nevermind. I fired up my nginx and tested this on ModSec3. Works like a charm. No further testing necessary.

**Comment by dune73** [comment]
I resolved the conflict in 901 and the PR is ready to be merged now.

Thank you for the cleanup @53cur3M3.

**Pull request merged**
