### PR TITLE
fix: FP with Oracle database error messages (951120 PL-1)

### PR DESCRIPTION
**Pull request by azurit**
I'm getting some FPs with rule `951120` matching Oracle database error messages, for example:
```
<URL>https://www.example.com/rainbow-loom-gumicky-trikolora-20721/</URL>
41-npr-devinska-kobyla-_-florora-693027.jpg
```
All Oracle error codes which i was able to find has 5 digits suffixed with a colon.

By the way, why we are matching this in case-insensitive mode? Matching it case-sensitive would prevent all my FPs.

### CODE REVIEW

**Comment by dune73** [comment]
I'm not sure the messages are case sensitive themselves. But I reckon a `\b` prefix would also help a big deal.

**Comment by dune73** [comment]
I think the terminating colon is trustworthy. But are we 100% sure? Would not another `\b` be good enough?

But happy to merge it like this if you are 100% sure.

**Comment by azurit** [comment]
@dune73 Yes, i am.

**Comment by azurit** [comment]
Closing in favor of https://github.com/coreruleset/coreruleset/pull/3685.

**Pull request closed without merging**
