### PR TITLE
933110: Add .phar and .phps to executable php files

### PR DESCRIPTION
**Pull request by terjanq**
This is a report from the BugBounty event. 

**Report id:** `33574D9R`

Payload:

```http
POST /juiceshop/file-upload HTTP/1.1
Host: sandbox.coreruleset.org
Content-Length: 176
Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryRGM420pTQRvLu0HE
Connection: close
x-crs-paranoia-level: 4
x-format-output: txt-matched-rules
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.41 Safari/537.36

------WebKitFormBoundaryRGM420pTQRvLu0HE
Content-Disposition: form-data; name="file"; filename=shell.phar

<?php echo '123'; ?>
------WebKitFormBoundaryRGM420pTQRvLu0HE--
```

### Explanation
Since PHP 7 the following extensions are recognized as exectuable PHP scripts:

```xml
<FilesMatch ".+\.ph(ar|p|tml)$">
    SetHandler application/x-httpd-php
</FilesMatch>
```

The rule doesn't recognize `.phar` nor `.phps` as executable PHP files. Although `.phps` is not considered executable now, it is for [lower version](https://www.tutorialspoint.com/php/php_apache_configuration.htm) of PHP.

### CODE REVIEW

**Comment by dune73** [comment]
### CRS Bug Bounty PR assessment

* **Rules affected** (list rules): FIXME
* **Paranoia Level addressed** (1, 2, 3, 4, full or explain): FIXME
* **FTW passes** (yes or no) : FIXME
* **Rule(s) picked for solution** (correct or not-correct or explain) : FIXME
* **Risk for false positives** (irrelevant, adequate, substantial or explain) : FIXME
* **Regular expression quality** (inspirational, decent base, needs work, adequate or explain) : FIXME
* **Documentation** (needs work, adequate or explain) : FIXME
* **Tests** (none or some or adequate) : FIXME
&nbsp;
* **Verdict** (Unusable, inspirational, usable, almost perfect or perfect) : FIXME

_This is not meant to be final. As a CRS dev, feel free to comment below and edit this form directly. As committer or observer, feel free to comment below with feedback and we will think about updating the assessment accordingly._

**Comment by lifeforms** [comment]
In the extension list https://github.com/swisskyrepo/PayloadsAllTheThings/tree/master/Upload%20Insecure%20Files/Extension%20PHP there are some extensions not yet caught by this rule: `.pht` , `.phpt`.

If this could be added it would be perfect.

**Comment by terjanq** [comment]
@lifeforms Added the two mentioned extensions. Additionally refactored descriptions of previous tests and added missing multipart tests. 

IMO there are too many tests that don't add anything to the test bundle and could be compressed to a smaller number of rules. I think it should be sufficient to refactor tests to:
* all extensions (.php, .php123, .phar, ...) 
* 1 positive and 1 negative test to test paths (maybe include something like 'aaa.txt/dangerous.php` as well) 
* 1 test to test `php...` gets blocked correctly
* 3 multipart tests as they are now
* all headers with a chosen extension (x-file-name, x-filename, x_filename, ...)
* 1-2 other negative tests 

Once this PR gets merged I could offer my help in refactoring those.

**Comment by dune73** [comment]
Thank you @terjanq.

We have updated our assessment. Regex is now adequate, as are the tests and the verdict is now Perfect.

Thank you for your offer to cut down on the excessive tests after merging this. I agree that would make a lot of sense.

Please open an issue and name yourself as a volunteer if you want to follow through. That way we do not lose track of this.

**Pull request merged**
