### PR TITLE
fix: comment false positive with 932236 by adding @

### PR DESCRIPTION
**Pull request by EsadCetiner**
closes https://github.com/coreruleset/coreruleset/issues/3387

### CODE REVIEW

**Review by franbuehler — APPROVED** [review]
Thank you for this contribution and also for the test. 
This PR looks good to me. 
If I call comm without an argument, this gives me an error, so this extension seems to be save: `comm: missing operand`

**Review by airween — CHANGES_REQUESTED** [review]
Seems that this PR modifies the operator's argument at 5 rules: 932235, 932260, 932236, 932239, 932237. But only one new regression tests has provided. @EsadCetiner: Could you add a new test case for each affected rules? Just for sure, then we can see what the effect is. Thanks!

**Review by airween — APPROVED** [review]
Looks good to me, thank you.

**Comment by dune73** [comment]
Changelog comment: 

fix: handle false positives with comm by adding @ character (932235 PL1, 932260 PL1, 932236 PL2,  932239 PL2, 932237 PL3) (Esad Cetiner)

**Pull request merged**
