### PR TITLE
perf: remove unnecessary chain rule and capture for 921180

### PR DESCRIPTION
**Pull request by EsadCetiner**
921180 works fine without the chained rule. It still correctly counts and blocks duplicate HTTP parameters

### CODE REVIEW

**Comment by dune73** [comment]
The chain is not there because of detection. The chain is there to get the `logdata` correctly. It's a pattern we use quite a bit these days. Is the logging right without the chain if you have several parameters, but only 1 duplication (look for order of parameters).

**Comment by EsadCetiner** [comment]
@dune73 Everything works the same regardless of how many parameters there are and the ordering. Although now ``msg`` is empty and ``matched_data`` keeps on logging accept for some reason (As shown below), I'll push a fix in sec.

Nginx log before fix:
``
2024/08/06 15:34:19 [info] 263792#263792: *4 ModSecurity: Warning. Matched "Operator `Gt' with parameter `1' against variable `TX:paramcounter_ARGS_NAMES:test' (Value: `2' ) [file "/etc/modsecurity/coreruleset/rules/REQUEST-921-PROTOCOL-ATTACK.conf"] [line "445"] [id "921180"] [rev ""] [msg "HTTP Parameter Pollution ()"] [data "Matched Data: accept found within TX:paramcounter_ARGS_NAMES:test: 2"] [severity "2"] [ver "OWASP_CRS/4.6.0-dev"] [maturity "0"] [accuracy "0"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-protocol"] [tag "paranoia-level/3"] [tag "OWASP_CRS"] [tag "capec/1000/152/137/15/460"] [hostname "127.0.0.1"] [uri "/"] [unique_id "172292245930.753196"] [ref ""], client: 127.0.0.1, server: _, request: "GET /?test=1&test=2 HTTP/1.1", host: "localhost:8080"
``

Apache log before fix:
``
[Tue Aug 06 15:33:49.523214 2024] [security2:error] [pid 263717:tid 140190341391936] [client 127.0.0.1:33858] [client 127.0.0.1] ModSecurity: Warning. Operator GT matched 1 at TX:paramcounter_ARGS_NAMES:test. [file "/etc/modsecurity/coreruleset/rules/REQUEST-921-PROTOCOL-ATTACK.conf"] [line "461"] [id "921180"] [msg "HTTP Parameter Pollution ()"] [data "Matched Data: accept found within TX:paramcounter_ARGS_NAMES:test: 2"] [severity "CRITICAL"] [ver "OWASP_CRS/4.6.0-dev"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-protocol"] [tag "paranoia-level/3"] [tag "OWASP_CRS"] [tag "capec/1000/152/137/15/460"] [hostname "localhost"] [uri "/"] [unique_id "ZrG1veDAH1Gwyak25iJueAAAAEg"]
``

Nginx log after fix:
``
[Tue Aug 06 15:56:08.130991 2024] [security2:error] [pid 264290:tid 139925637744192] [client 127.0.0.1:37830] [client 127.0.0.1] ModSecurity: Warning. Operator GT matched 1 at TX:paramcounter_ARGS_NAMES:test. [file "/etc/modsecurity/coreruleset/rules/REQUEST-921-PROTOCOL-ATTACK.conf"] [line "461"] [id "921180"] [msg "HTTP Parameter Pollution (TX:paramcounter_ARGS_NAMES:test)"] [data "Matched Data: 2 found within TX:paramcounter_ARGS_NAMES:test: 2"] [severity "CRITICAL"] [ver "OWASP_CRS/4.6.0-dev"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-protocol"] [tag "paranoia-level/3"] [tag "OWASP_CRS"] [tag "capec/1000/152/137/15/460"] [hostname "localhost"] [uri "/"] [unique_id "ZrG6-HpfNDnkDKy8BJvK6AAAAEA"]
``

Apache log after fix:
``
2024/08/06 15:54:25 [info] 264232#264232: *1 ModSecurity: Warning. Matched "Operator `Gt' with parameter `1' against variable `TX:paramcounter_ARGS_NAMES:test' (Value: `2' ) [file "/etc/modsecurity/coreruleset/rules/REQUEST-921-PROTOCOL-ATTACK.conf"] [line "445"] [id "921180"] [rev ""] [msg "HTTP Parameter Pollution (TX:paramcounter_ARGS_NAMES:test)"] [data "Matched Data: 2 found within TX:paramcounter_ARGS_NAMES:test: 2"] [severity "2"] [ver "OWASP_CRS/4.6.0-dev"] [maturity "0"] [accuracy "0"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-protocol"] [tag "paranoia-level/3"] [tag "OWASP_CRS"] [tag "capec/1000/152/137/15/460"] [hostname "127.0.0.1"] [uri "/"] [unique_id "172292366579.538854"] [ref ""], client: 127.0.0.1, server: _, request: "GET /?test=1&test=2 HTTP/1.1", host: "localhost:8080"
``

**Comment by dune73** [comment]
Thanks for your extensive assessment. I realize the original implementation was broken (`HTTP Parameter Pollution ()`) and your fix is not fixing this. But I think you get rid of the bug via a simpler logging message and I think this is good enough. I'll let others formally approve this, but I am OK with the PR.

**Review by azurit — APPROVED** [review]

**Comment by azurit** [comment]
This is, probably, a leftover from the time when a rule was more complex.

**Comment by azurit** [comment]
@EsadCetiner Good catch, thanks!

**Pull request merged**
