### PR TITLE
Cleaned up quoting in tests for 920120

### PR DESCRIPTION
**Pull request by theseion**
Related to https://github.com/coreruleset/coreruleset/pull/2360

This is PR 2 of 4 that replace https://github.com/coreruleset/coreruleset/pull/2360.

### CODE REVIEW

**Comment by airween** [comment]
Why is important to escape the `Accept` header? I don't see the reason in the mentioned issue.

Btw, it's a good idea to add escape to all header, but then we should add to all header :)

**Comment by theseion** [comment]
By "escape" do you mean "quote"? I think it's a good idea because there can be arbitrary characters in there, especially `*`, which marks an anchor in YAML.

But TBH, I just wanted the quoting to be consistent (some `Accept` and `User-Agent` headers were quoted after @fzipi's change, and some weren't).

I can update this PR to quote all headers. @fzipi @fgsch?

**Comment by airween** [comment]
> By "escape" do you mean "quote"? I think it's a good idea because there can be arbitrary characters in there, especially `*`, which marks an anchor in YAML.

sorry, yes - I thought quote, not escape :).

Thanks!

**Review by fzipi — APPROVED** [review]
LGTM.

**Pull request merged**
