### PR TITLE
add CHANGES and CONTRIBUTORS for 4.0

### PR DESCRIPTION
**Pull request by lifeforms**

### CODE REVIEW

**Comment by dune73** [comment]
Hear, hear!

**Comment by dune73** [comment]
Can we do the PCRE improvements towards RE2/HyperScan as an imporant change?

**Comment by dune73** [comment]
Actually early blocking is also an important change.

As is the renaming of the anomaly scoring variables and the overhauling of the reporting rules in 9801xx.

**Comment by lifeforms** [comment]
Yes! Can you move it up! And feel free to edit.

**Comment by lifeforms** [comment]
I see I made a typo in that line anyway.

**Pull request merged**
