### PR TITLE
fix: PHP errors data file

### PR DESCRIPTION
**Pull request by azurit**
Some of the patterns in `php-errors.data` are too common to be in PL1 so i'm moving them into PL2. I also removed a whitespace from the beginning of few patters as it's trimmer by modsec anyway.

### CODE REVIEW

**Comment by azurit** [comment]
Fixes: https://github.com/coreruleset/wordpress-rule-exclusions-plugin/pull/10

**Comment by dune73** [comment]
Thank you. +1 on the trimming away of the whitespace prefix that really does not add much.

I am wondering if it is worth to add a new rule to avoid some FPs, but it's true that the FPs are quite obvious.

One option would be to simply forget about the signatures - just how important are they really, namely the "The function" has an extended variant - but if we assume they are important, than I think an additional PL2 rule is warranted.

Calling in the dev channel to see if we can get more opinions.

**Review by dune73 — APPROVED** [review]

**Comment by azurit** [comment]
> One option would be to simply forget about the signatures - just how important are they really, namely the "The function" has an extended variant - but if we assume they are important, than I think an additional PL2 rule is warranted.

I agree with this. Anyway, there are lots of error messages and i wasn't able to check them all. I'm sure there will be more FPs so the list of error messages for PL2 will be rising.

**Comment by theseion** [comment]
Sounds good to me. If you think that there will be more messages to add to the PL2 list then it's probably worth it. I also agree that the whitespace doesn't add additional context. @azurit, did you mean that `@pmFromFile` trims whitespace at the beginning of lines anyway?

**Comment by azurit** [comment]
@theseion Yes, from the docs:
_any whitespace trimmed from both the beginning and the end_

**Comment by dune73** [comment]
I confirm that behaviour.

**Comment by dune73** [comment]
Time to merge than.

Thank you @azurit.

**Pull request merged**
