### PR TITLE
#2431 Added Krzana bot

### PR DESCRIPTION
**Pull request by deepshikha-s**
Solves #2431

### CODE REVIEW

**Comment by dune73** [comment]
Thank you for your contribution @deepshikha-s. Would you mind putting this in alphabetical order?

**Comment by azurit** [comment]
@deepshikha-s Also, please put a space after the comment sign (`#`).

**Comment by deepshikha-s** [comment]
I have made the changes.

**Comment by dune73** [comment]
Looks good. Thank you for the fix. Merging now.

**Pull request merged**
