### PR TITLE
Update REQUEST-920-PROTOCOL-ENFORCEMENT.conf

### PR DESCRIPTION
**Pull request by azurit**
Added a hashtag character into allowed ones, real-world example:
Content-Type: application/soap+xml; charset=utf-8; action="urn:localhost-hwh#getQuestions"

### CODE REVIEW

**Comment by fzipi** [comment]
Thanks @azurit !

Are you able to provide some test also?

**Comment by azurit** [comment]
What kind of test do you mean?

**Comment by fzipi** [comment]
ftw test. No worries, just if you had :)

**Comment by fzipi** [comment]
Hi @azurit ! We are in the process of merging this one. Could you please rebase to next official release, `v3.4/dev`? Thanks!

**Comment by azurit** [comment]
@fzipi https://github.com/coreruleset/coreruleset/pull/1839

**Comment by dune73** [comment]
Closing in favor of #1839.

**Pull request closed without merging**
