### PR TITLE
feat: add dependency checks to PRs and issues

### PR DESCRIPTION
**Pull request by theseion**
GitHub does not (yet) have the ability to block PRs / issues as dependencies of other PRs issues. This commit uses gregsdennis/dependency-action as a simple workaround.

Now, wording like "blocks #123" or "depends on #123" will add a check for the completion of the dependent PR / issue.

New GH action used: https://github.com/marketplace/actions/pr-dependency-check
GH feature request with the currently available workarounds: https://github.com/orgs/community/discussions/4477#discussioncomment-1039627

### CODE REVIEW

**Comment by dune73** [comment]
This sounds nifty.

Will this cover only the initial issue / PR message, only the title, or any comment?

@RedXanadu Where do we have to document this?

**Comment by dune73** [comment]
If it happens via a first comment update, that's cool. And I do not mind either way. We just need to know - and document it.

**Comment by theseion** [comment]
Yes. Although I see this primarily as an tool for us core devs, so putting it in the Wiki is probably enough.

**Comment by dune73** [comment]
Would not it be part of the documentation that also covers the CI/CD testing?

**Comment by theseion** [comment]
Is there such a thing? I couldn't find anything in the docs...

**Comment by dune73** [comment]
I thought @RedXanadu would find something...

If not, it may be time to start a new section in one of the docs.

**Review by fzipi — APPROVED** [review]

**Comment by RedXanadu** [comment]
Sorry, late to the party.

This should be documented as an option under "Making Changes" in the "Contribution Guidelines", e.g.:

> If an issue or PR is dependent on another then this relationship can be expressed, in a way that our GitHub repository will understand, by writing "depends on #1234" or "blocked by #1234" in the opening comment.

Is that a correct understanding of what has been proposed here?

Separately, it would be good for someone to document all of the GitHub Lang stuff that underpins CRS in a wiki page, as I would bet that a majority of CRS devs don't have a clue about it… (I certainly don't). Some internal-facing reference material would be very welcome. Does anyone have both the knowledge and the time to write that?

@theseion How does this work for issues, as they have no checks to fail? I tested it on the [first comment of an issue](https://github.com/coreruleset/coreruleset/issues/3288#issue-1873131754) and couldn't see a change.

**Comment by theseion** [comment]
>Is that a correct understanding of what has been proposed here?

Yes.

>Separately, it would be good for someone to document all of the GitHub Lang stuff that underpins the internal CRS project/repo workings in a wiki page, as I would bet that a majority of CRS devs don't have a clue about it… (I certainly don't). Some internal-facing reference material would be very welcome. Does anyone have both the knowledge and the time to write that?

I can help with that, although I'm not sure what you want covered. Can you give me a list of topics?

>@theseion How does this work for issues, as they have no checks to fail? I tested it on the https://github.com/coreruleset/coreruleset/issues/3288#issue-1873131754 and couldn't see a change. (Tested it on a PR and it worked as intended.)

TBH, I only made it work for PRs. But it should only be a small thing to add to issues.

**Comment by RedXanadu** [comment]
Hmm… I think that, for _any_ time we use a GitHub Workflow/Action/Automation, we should have an internal note (for the attention of CRS devs) stating what it is and what maintenance or modifications it may need. So, I think a list of topics would be _everything_ we're currently doing with GitHub magic, so that the knowledge can be decentralised. I've added this as a workshop suggestion for the retreat, as I think this would be better as an in-person group discussion/workshop, as the aim should be to spread the knowledge of these Workflows and how they function.

**Comment by theseion** [comment]
Good idea. Definitely better to discuss in a group.

**Pull request merged**
