### PR TITLE
feat: Split Node-Validator keywords functionally

### PR DESCRIPTION
**Pull request by RubieV**
This improvement adds further consistency to https://github.com/coreruleset/coreruleset/pull/2088

The PL1 rule (`941180`) of Node-Validator keywords contains both evident attack fragments, i.e. `document.cookie`, as well as comment payloads, i.e. `<!--`.

This change moves all comment payloads to the PL2 rule (`941181`) that already contains the comment closing tag `-->`. 

This makes the PL1 rule in line with the goal of PL1, and makes the already existing PL2 rule consistent with the goal of having `comment` payloads.

### CODE REVIEW

**Comment by RedXanadu** [comment]
Rebased to resolve merge conflict.

**Comment by RedXanadu** [comment]
Now that the comment detection has been moved out of rule 941180 and into rule 941181, I think what is required here is to move the comment-related tests out of `941180.yaml`.

(There are two that I can see: 941180-4 and 9421180-5, although only 9421180-5 (the test title needs correcting) is failing.)

**Comment by RedXanadu** [comment]
@dune73 This can wait until post-v4, right? If so, then yes, I can take another look.

**Comment by dune73** [comment]
OK, then let's add the post-4.0 tag and leave it as is for the time being.

**Comment by RedXanadu** [comment]
Cool, thanks. I'll re-base it and take another look when I can.

**Comment by dune73** [comment]
Ready to reactivate this @RedXanadu?

**Comment by RedXanadu** [comment]
I don't remember what this was about :sweat_smile:  But yes, I can take a look.

**Comment by dune73** [comment]
Thank you @RedXanadu.

**Comment by fzipi** [comment]
@dune73 @RedXanadu We've been adding this one since September 2023 to the agenda. And it is originally from 2022. Are we thinking on merging, or we just close?

**Comment by RedXanadu** [comment]
No movement on my part; still on my todo list.

**Pull request closed without merging**
