### PR TITLE
Add various SQL operators for 942120

### PR DESCRIPTION
**Pull request by karelorigin**
Block attempts to use various SQL operators, some specific to certain database management systems.

### CODE REVIEW

**Comment by azurit** [comment]
Hi @terjanq, thanks for sending this!

**Comment by azurit** [comment]
Hi @karelorigin , thanks for sending this!

**Comment by dune73** [comment]
@karelorigin would you mind quoting the bug bounty ID (without the prefix) here?

**Comment by karelorigin** [comment]
Hi @dune73, the ID is the suffix of the branch name used in this PR (4L7DPMMR)

**Comment by dune73** [comment]
Actually no, since there is an additional online spreadsheet involved where Intigrity and we track the PRs. And we would now have to go through all the reports to find out which ones link to this PR here (and the website does not allow to search for links AFAICT).
So please do us a favor and name them here.

**Comment by dune73** [comment]
Thank you very much. We have this now for all the new PRs.

**Comment by dune73** [comment]
### CRS Bug Bounty PR assessment

* **Rules affected** (list rules): FIXME
* **Paranoia Level addressed** (1, 2, 3, 4, full or explain): FIXME
* **FTW passes** (yes or no) : FIXME
* **Rule(s) picked for solution** (correct or not-correct or explain) : FIXME
* **Risk for false positives** (irrelevant, adequate, substantial or explain) : FIXME
* **Regular expression quality** (inspirational, decent base, needs work, adequate or explain) : FIXME
* **Documentation** (needs work, adequate or explain) : FIXME
* **Tests** (none or some or adequate) : FIXME
&nbsp;
* **Verdict** (Unusable, inspirational, usable, almost perfect or perfect) : FIXME

_This is not meant to be final. As a CRS dev, feel free to comment below and edit this form directly. As committer or observer, feel free to comment below with feedback and we will think about updating the assessment accordingly._

**Comment by lifeforms** [comment]
Thank you!

**Pull request merged**
