### PR TITLE
docs: update changelog file to markdown

### LINKED ISSUE #2529: Convert CHANGES to markdown
It's easier on the eyes.

Also fix references to it, for instance from the release blog and installation page, and probably documentation.

### PR DESCRIPTION
**Pull request by fzipi**
Signed-off-by: Felipe Zipitria <felipe.zipitria@owasp.org>

Fixes #2529 .

### CODE REVIEW

**Comment by dune73** [comment]
Hold on. This merge was a bit quick.

It transformed `== title ==` to `## title ##`, which is not correct but still displays OK.

However, there is also a case where

```bash
* Updated the SQL Injection filters to detect boolean attacks (1<2, foo == bar, etc..)
```

was transformed to

```bash
* Updated the SQL Injection filters to detect boolean attacks (1<2, foo ## bar, etc..)
```

I see two optionss: Rollback or new PR fixing this.

Opinions @fzipi / @lifeforms ?

**Comment by lifeforms** [comment]
Oh, I did not notice that, good catch!

I think it's better to make a new PR to fix it. Do you have spare cycles @fzipi ?

**Comment by fzipi** [comment]
Sure!

**Comment by dune73** [comment]
Thank you.

**Pull request merged**
