### PR TITLE
Move 941310 from PL1 to PL2

### PR DESCRIPTION
**Pull request by franbuehler**
This PR is a proposal for issue #1942. We can discuss there if this is the correct solution.
This PR moves rule 941310 from PL1 to PL2, because it has a lot of false positives with Russian letters and German Umlaute.

### CODE REVIEW

**Comment by franbuehler** [comment]
Meeting decision March: https://github.com/coreruleset/coreruleset/issues/2008#issuecomment-788239186:
@airween volunteers to review this PR after @franbuehler provided a curl example.

**Comment by dune73** [comment]
@franbuehler did you send the curl example to @airween directly or did this get lost?

**Comment by franbuehler** [comment]
@dune73, I was not able to find a curl example. I tried to reproduce it in the browser with the application where I found the false positives in the log. I also tried with Max explanation but it does not work for me. My environment seems to encode the correct way.
See the linked issue.

**Comment by dune73** [comment]
Thank you. I propose we leave this PR open for a bit longer until your discussion with @thesion is over in issue #1942.

**Comment by dune73** [comment]
Time to put this back on the table?

**Comment by franbuehler** [comment]
Meeting decision June (https://github.com/coreruleset/coreruleset/issues/2074#issuecomment-856173925):
@franbuehler and @theseion will discuss on their call if this PR should still be merged

**Comment by franbuehler** [comment]
I would close this PR here for 2 reasons:

1. We have the new chained rule from PR #2107 at PL1 (PL1 is my proposal), which also has a good coverage of the attack.
2. The vulnerability is rare because it only appears on an incorrectly configured Tomcat. I would not risk a possible FP on PL2 for this rare vulnerability..

**Comment by franbuehler** [comment]
We agree on closing this PR here. PR #2107 solves the problem.
https://github.com/coreruleset/coreruleset/issues/2141#issuecomment-874288876

**Pull request closed without merging**
