### PR TITLE
Regenerate rules

### PR DESCRIPTION
**Pull request by theseion**
This PR cleans up data files and rules as necessary so that all rules are up to date.

@lifeforms please look at 932150, 942290 specifically
@fzipi please look at 932300 specifically

### CODE REVIEW

**Comment by fzipi** [comment]
Ugh, sorry I don't have my laptop till the weekend. Why did we removed the !$ on 932300?

**Comment by theseion** [comment]
> Ugh, sorry I don't have my laptop till the weekend. Why did we removed the !$ on 932300?

It's an empty suffix comment. The regex is exactly the same without it.

**Review by fzipi — APPROVED** [review]
LGTM on 932300.

**Comment by fzipi** [comment]
@lifeforms I think we are waiting on your approval here.

**Comment by lifeforms** [comment]
OK from me!

**Comment by lifeforms** [comment]
A relevant issue was described in: #2756

**Pull request merged**
