### PR TITLE
chore: add Karel to 'Developers'

### PR DESCRIPTION
**Pull request by karelorigin**
@dune73 suggested creating this PR to discuss the possibility of giving me commit rights to the CRS organisation.

### CODE REVIEW

**Review by fzipi — APPROVED** [review]
Bibiti bobiti!

**Comment by dune73** [comment]
Thank you for the welcome PR @karelorigin and thank you for requesting my review @fzipi.  

Maybe @lifeforms wants to point out that the developers section of CONTRIBUTORS.md is in alphabetical order.

Other than that, the tests seems to have passed, so I am OK with merging.

**Review by dune73 — APPROVED** [review]

**Comment by karelorigin** [comment]
Ah! The entries seemed random, but apparently they are sorted on surname :sweat_smile:. Fixed it just now.

**Comment by lifeforms** [comment]
Welcome! 😉

**Pull request merged**
