### PR TITLE
fix(path): update path in util to subdirectory

### PR DESCRIPTION
**Pull request by fzipi**
Signed-off-by: Felipe Zipitria <felipe.zipitria@owasp.org>

Fixes remainings from path change.

### CODE REVIEW

**Comment by dune73** [comment]
Thanks for spotting and fixing this.

It seems 942440 remains unfixed, though.

**Comment by dune73** [comment]
Thank you. Looks good. Merging now.

**Comment by fzipi** [comment]
@dune73 Did you saw something additional, or just missed the button? 🤣

**Comment by theseion** [comment]
Oops! Thanks! :)

**Pull request merged**
