### PR TITLE
Fixing few SQLi related false negatives

### PR DESCRIPTION
**Pull request by azurit**
1. Adding more error based SQLi MySQL functions:
- geometrycollection
- gtid_subset
- linestring
- multilinestring
- multipoint
- multipolygon
- polygon
2. Catch MySQL errors such as this (this one was returned by `gtid_subset` function):
`ERROR 1772 (HY000): Malformed GTID set specification 'secret_password'.`
Here is a list of all error codes: https://mariadb.com/kb/en/mariadb-error-codes/
3. Adding tests for all 951 rules.

### CODE REVIEW

**Comment by azurit** [comment]
By the way, i would split rule `942150` into two rules:
 - new phase 1 rule which will include function names which won't do much FPs (which are not based on common words, like mentioned `gtid_subset`)
 - current rule with rest of the keywords (it's in phase 2)

**Comment by fzipi** [comment]
@azurit What do you think about creating an issue about your comment here (splitting 942150), so we can merge this one and don't forget?

**Comment by fzipi** [comment]
Also, would be awesome if you can add tests for the 951 rules (using the `/anything` endpoint in httpbin).

**Comment by fzipi** [comment]
@azurit Any news on this? Do you need help?

**Comment by azurit** [comment]
No, thanks, i will do it tomorrow. Sorry for the delay.

**Comment by azurit** [comment]
@fzipi all done:
https://github.com/coreruleset/coreruleset/issues/2468

**Pull request merged**
