### PR TITLE
fix(942120): add collate operator

### PR DESCRIPTION
**Pull request by terjanq**
This is a patch for a bypass from the BugBounty event.

**Report id:** Report id: `R5U7LYM2`

### Bypass payload:
```http
POST /juiceshop/rest/user/login HTTP/1.1
Host: sandbox.coreruleset.org
Content-Length: 48
Content-Type: application/json
User-Agent: curl
Connection: close
x-crs-paranoia-level: 3
x-format-output: txt-matched-rules
accept: text/js

{"email":"admin@juice-sh.op' collate nocase --"}
```

### Explanation:
SQLite [collate](https://www.sqlite.org/datatype3.html#collating_sequences) can have 3 different valuses: `binary`, `nocase`, `rtrim`. The following syntax is also a valid query `collate"nocase"` hence the added rule is: `\bcollate\W+(?:binary|nocase|rtrim)\b`.

As a bonus, I also added two rules for different SQL databases. Most often they look like `collate utf8mb4_general_ci` so I added the rule `\bcollate\W+\w*?_` that will only trigger if there is `_` just after a word-like sequence and the rule ``\bcollate\W*?(?:U&)?[\"'`]`` that triggers when a string starts just after the sequence of non-word characters. The following payloads will be blocked by the rule:
-  `collate    utf8mb4_general_ci`
-  ``collate`utf8mb4_general_ci` ``
-  `collate"_ `
-  `collate _ `
-  `collate U&"\0441\043B\043E\043D"`
-  `collate"\utf8mb4_general_ci"`

These will not:
- `collate foo`
- `collate_xyz`

### Fix caveats
I didn't find any caveats for the fix.

### CODE REVIEW

**Comment by dune73** [comment]
### CRS Bug Bounty PR assessment

* **Rules affected** (list rules): FIXME
* **Paranoia Level addressed** (1, 2, 3, 4, full or explain): FIXME
* **FTW passes** (yes or no) : FIXME
* **Rule(s) picked for solution** (correct or not-correct or explain) : FIXME
* **Risk for false positives** (irrelevant, adequate, substantial or explain) : FIXME
* **Regular expression quality** (inspirational, decent base, needs work, adequate or explain) : FIXME
* **Documentation** (needs work, adequate or explain) : FIXME
* **Tests** (none or some or adequate) : FIXME
&nbsp;
* **Verdict** (Unusable, inspirational, usable, almost perfect or perfect) : FIXME

_This is not meant to be final. As a CRS dev, feel free to comment below and edit this form directly. As committer or observer, feel free to comment below with feedback and we will think about updating the assessment accordingly._

**Comment by lifeforms** [comment]
Merge after conflicts resolved.

**Comment by terjanq** [comment]
@lifeforms resolved conflicts.

**Comment by dune73** [comment]
Assigning @lifeforms  based on the separate spreadsheet in our drive.

**Comment by fzipi** [comment]
@lifeforms What are we going to do with this? If we don't merge quickly, we might get more conflicts ...

**Comment by lifeforms** [comment]
I'm terribly sorry that I didn't react sooner. We have a conflict again. I tried to resolve it, but Git outsmarts me. There seem to be things happening to rules 942520, 942521, 942522, which are unrelated to the rule 942120. I don't understand why this is even showing up, maybe it has to do with some noise in the commits.

@terjanq Do you think you can resolve the conflict one more time? This time I will merge it immediately. Thank you so much!

**Comment by lifeforms** [comment]
I've been looking at the failing tests for rule 942521.

The changed files https://github.com/coreruleset/coreruleset/pull/2584/files shows:

- Rule 942521 has been deleted
- Rule 942522 has been deleted

These two rules were added earlier on 24 May by terjanq.

Was it intended to remove these rules (were they combined into rule 942120? I think not, as far as I can see), or maybe it was a mistake in Git branching?

Unless I'm wrong, I think rules 942521 and 942522 should be brought back.
That would solve the test issues and then this issue can be merged.

I can fix the PR by re-adding the rules, feel free to ask me to do it.

**Comment by fzipi** [comment]
Yes, this was a mistake I did in the gh UI yesterday. That's exactly the fix.

**Comment by lifeforms** [comment]
I reverted the deleted rules. Tests are succeeding! Merge time! 🥳 Thank you @terjanq for the contribution.

**Comment by terjanq** [comment]
As far as I remember Github incorrectly marks .data files as branched ones hence trying to auto-resolve conflicts does a lot of mess. The only way was to just manually add all the files again. Nice to see it merged :)

**Pull request merged**
