### PR TITLE
fix(sqli): additional sqli auth bypasses

### PR DESCRIPTION
**Pull request by rekter0**
fixes related to `8PPEUO5P` and partial for `5UXE4RK0`

### CODE REVIEW

**Comment by terjanq** [comment]
It seems that the patch won't protect against `''glob rowid-1--` for example.

**Comment by dune73** [comment]
### CRS Bug Bounty PR assessment

* **Rules affected** (list rules): FIXME
* **Paranoia Level addressed** (1, 2, 3, 4, full or explain): FIXME
* **FTW passes** (yes or no) : FIXME
* **Rule(s) picked for solution** (correct or not-correct or explain) : FIXME
* **Risk for false positives** (irrelevant, adequate, substantial or explain) : FIXME
* **Regular expression quality** (inspirational, decent base, needs work, adequate or explain) : FIXME
* **Documentation** (needs work, adequate or explain) : FIXME
* **Tests** (none or some or adequate) : FIXME
&nbsp;
* **Verdict** (Unusable, inspirational, usable, almost perfect or perfect) : FIXME

_This is not meant to be final. As a CRS dev, feel free to comment below and edit this form directly. As committer or observer, feel free to comment below with feedback and we will think about updating the assessment accordingly._

**Comment by fzipi** [comment]
@lifeforms Can you run this on some traffic to see how it behaves?

**Comment by lifeforms** [comment]
Updated rule 942180 and running it now on 3 machines.

**Comment by lifeforms** [comment]
I looked at the logs. I'm impressed that all my 942180 logs truly point to extensive SQLi attempts.

Here are some:

```
[id \"942180\"] [msg \"Detects basic SQL authentication bypass attempts 1/3\"] [data \"Matched Data: '=' found within ARGS:type: post') AND EXTRACTVALUE(8857,CONCAT(0x5c,0x71707a6b71,(SELECT (ELT(8857=8857,1))),0x7162707171)) AND ('oiwD'='oiwD\"]

[id \"942180\"] [msg \"Detects basic SQL authentication bypass attempts 1/3\"] [data \"Matched Data: ' AND EXTRACTVALUE(8 found within ARGS:type: post' AND EXTRACTVALUE(8857,CONCAT(0x5c,0x71707a6b71,(SELECT (ELT(8857=8857,1))),0x7162707171)) AND 'Psir'='Psir\"]

[id \"942180\"] [msg \"Detects basic SQL authentication bypass attempts 1/3\"] [data \"Matched Data: '=' found within ARGS:type: post') AND 6300=CAST((CHR(113)||CHR(112)||CHR(122)||CHR(107)||CHR(113))||(SELECT (CASE WHEN (6300=6300) THEN 1 ELSE 0 END))::text||(CHR(113)||CHR(98)||CHR(112)||CHR(113)||CHR(113)) AS NUMERIC) AND ('XYPW'='XYPW\"]

[id \"942180\"] [msg \"Detects basic SQL authentication bypass attempts 1/3\"] [data \"Matched Data: '=' found within ARGS:type: post') AND 3718 IN (SELECT (CHAR(113) CHAR(112) CHAR(122) CHAR(107) CHAR(113) (SELECT (CASE WHEN (3718=3718) THEN CHAR(49) ELSE CHAR(48) END)) CHAR(113) CHAR(98) CHAR(112) CHAR(113) CHAR(113))) AND ('xIHb'='xIHb\"].

[id \"942180\"] [msg \"Detects basic SQL authentication bypass attempts 1/3\"] [data \"Matched Data: '=' found within ARGS:type: post') AND 8350=(SELECT UPPER(XMLType(CHR(60)||CHR(58)||CHR(113)||CHR(112)||CHR(122)||CHR(107)||CHR(113)||(SELECT (CASE WHEN (8350=8350) THEN 1 ELSE 0 END) FROM DUAL)||CHR(113)||CHR(98)||CHR(112)||CHR(113)||CHR(113)||CHR(62))) FROM DUAL) AND ('CooS'='CooS\"]

[id \"942180\"] [msg \"Detects basic SQL authentication bypass attempts 1/3\"] [data \"Matched Data: '=' found within ARGS:id: 14557002' AND 8952 IN (SELECT (CHAR(113) CHAR(98) CHAR(106) CHAR(120) CHAR(113) (SELECT (CASE WHEN (8952=8952) THEN CHAR(49) ELSE CHAR(48) END)) CHAR(113) CHAR(113) CHAR(112) CHAR(106) CHAR(113))) AND 'yRYr'='yRYr\"]

[id \"942180\"] [msg \"Detects basic SQL authentication bypass attempts 1/3\"] [data \"Matched Data: '=' found within ARGS:notice_id: 220' AND 7388=CAST((CHR(113)||CHR(107)||CHR(118)||CHR(118)||CHR(113))||(SELECT (CASE WHEN (7388=7388) THEN 1 ELSE 0 END))::text||(CHR(113)||CHR(122)||CHR(120)||CHR(113)||CHR(113)) AS NUMERIC) AND 'furx'='furx\"] 

[id \"942180\"] [msg \"Detects basic SQL authentication bypass attempts 1/3\"] [data \"Matched Data: '=' found within ARGS:css: public:normalize.css,public:fa.css,public:core.less,public:app.less') AND 7846 IN (SELECT (CHAR(113) CHAR(120) CHAR(106) CHAR(112) CHAR(113) (SELECT (CASE WHEN (7846=7846) THEN CHAR(49) ELSE CHAR(48) END)) CHAR(113) CHAR(107) CHAR(112) CHAR(122) CHAR(113))) AND ('pcDJ'='pcDJ\"]
```

That's quite some. Very nice that this is all detected by the rule! 🥳

`curl "http://localhost/?test=a'='b"` is a positive for this rule, so it might be a source of false positives. However, libinjection also triggers on that pattern! So many payloads like this are already blocked - it is not necessarily a new FP (except if you have a high threshold set, which is not recommended).

Note though: I have many exclusions for my hosted apps, so I may be missing some false positives.

I'm tempted to try it out, and if during testing of nightly and the next RC it appears to be unusably trigger happy, we can move it to PL2.

**Comment by dune73** [comment]
This is not really solving the HTTP Parameter Pollution problem in `5UXE4RK0`.

See https://github.com/coreruleset/coreruleset/pull/2747 for a solution.

**Pull request merged**
