### PR TITLE
Added sensitive files

### PR DESCRIPTION
**Pull request by gwen001**
Reports:
* `EH5C5EUO`
* `4E0SK9T6`
* `ZITHAVYB`
* `C4AKMJX5`

I merged all those reports in 1 PR, and also added files listed by @dune73 

Thank you.

### CODE REVIEW

**Comment by dune73** [comment]
Please notice that `JW2SU88A` is also covered in PR #2562.

**Comment by gwen001** [comment]
You're right and I think it's a mistake. `JW2SU88A` should not be here, but only in #2562.
Thanks for the notification, I'm updating the original description.

**Comment by dune73** [comment]
Thanks!

**Comment by dune73** [comment]
### CRS Bug Bounty PR assessment

* **Rules affected** (list rules): FIXME
* **Paranoia Level addressed** (1, 2, 3, 4, full or explain): FIXME
* **FTW passes** (yes or no) : FIXME
* **Rule(s) picked for solution** (correct or not-correct or explain) : FIXME
* **Risk for false positives** (irrelevant, adequate, substantial or explain) : FIXME
* **Regular expression quality** (inspirational, decent base, needs work, adequate or explain) : FIXME
* **Documentation** (needs work, adequate or explain) : FIXME
* **Tests** (none or some or adequate) : FIXME
&nbsp;
* **Verdict** (Unusable, inspirational, usable, almost perfect or perfect) : FIXME

_This is not meant to be final. As a CRS dev, feel free to comment below and edit this form directly. As committer or observer, feel free to comment below with feedback and we will think about updating the assessment accordingly._

**Comment by lifeforms** [comment]
Thank you for the PR!

**Pull request merged**
